/**
 * Storyblok TypeScript types
 *
 * Generated by: bun run storyblok:sync
 *
 * This file will be auto-generated from your Storyblok space.
 * Do not edit manually.
 */

// Placeholder types until generated
export interface StoryblokStory<T = unknown> {
  id: number;
  uuid: string;
  name: string;
  slug: string;
  full_slug: string;
  content: T;
  created_at: string;
  published_at: string | null;
  first_published_at: string | null;
}

// Re-export component types
export type { ShadcnButtonBlok } from "../shadcn/Button";
export type { ShadcnCardBlok } from "../shadcn/Card";
export type { ShadcnHeroBlok } from "../shadcn/Hero";
export type { PresetHeroDefaultBlok } from "../presets/HeroDefault";
export type { DevScenarioPickerBlok } from "../dev/ScenarioPicker";
