export function caseStudies2SectionBuilderRaw() {
  return {
    _uid: "05289be4-5693-482a-8441-ece56a48fe84",
    name: "case-studies-2",
    items: [
      {
        _uid: "d3f97488-3074-4f29-90d9-6549f1a8d43f",
        name: "header",
        items: [
          {
            _uid: "a2140424-36b4-4e4b-ac0b-f2fac76a3d7f",
            name: "hero-wrapper",
            items: [
              {
                _uid: "6d7b2000-4d4f-41af-bcff-cd82a2c60b20",
                size: "base",
                align: "center",
                color: "primary",
                styles: [],
                weight: "semibold",
                content: "4500+ Satisfied Customers",
                element: "p",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: "1dc19d40-7dfb-4dca-8f42-f923c83e0b79",
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: "4fb8f4fc-e467-43cb-8bb9-c5c83533f549",
                  color: "",
                  plugin: "native-color-picker",
                },
                line_height: "normal",
                letter_spacing: "wide",
                data_field_name: "description",
                data_entry_section: "study",
                _editable:
                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "6d7b2000-4d4f-41af-bcff-cd82a2c60b20", "id": "141503480340431"}-->',
              },
              {
                _uid: "048b6fcd-b9ba-44f9-a745-d278cca400da",
                size: "4xl",
                align: "center",
                color: "primary",
                styles: [
                  {
                    gap: "",
                    _uid: "9a220236-eb16-4dbc-8e9f-d8a9c7e73c0f",
                    wrap: false,
                    align: "",
                    width: "",
                    border: [],
                    height: "",
                    margin: [],
                    shadow: "",
                    display: "",
                    justify: "",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "",
                    max_width: "",
                    min_width: "",
                    text_size: "5xl",
                    breakpoint: "md",
                    max_height: "",
                    min_height: "",
                    border_color: "",
                    border_style: "",
                    border_width: "",
                    _editable:
                      '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "9a220236-eb16-4dbc-8e9f-d8a9c7e73c0f", "id": "141503480340431"}-->',
                  },
                ],
                weight: "semibold",
                content: "Real results from real users",
                element: "h2",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: "ed4ae582-8bed-433f-aa99-a9cf46a193f2",
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: "567d6979-b1d1-403e-872b-1f80afe223e9",
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                line_height: "",
                letter_spacing: "",
                data_field_name: "name",
                data_entry_section: "study",
                _editable:
                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "048b6fcd-b9ba-44f9-a745-d278cca400da", "id": "141503480340431"}-->',
              },
            ],
            styles: [
              {
                gap: "gap-6",
                _uid: "bff60b69-d50c-4207-96fb-4662acfb77ce",
                wrap: false,
                align: "items-center",
                width: "",
                height: "",
                margin: "",
                display: "",
                justify: "justify-start",
                padding: [],
                component: "shared_styles_breakpoint_options",
                direction: "flex-col",
                max_width: "max-w-2xl",
                min_width: "",
                text_size: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "bff60b69-d50c-4207-96fb-4662acfb77ce", "id": "141503480340431"}-->',
              },
            ],
            component: "shared_shadcn_container",
            container_as: "hgroup",
            _editable:
              '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "a2140424-36b4-4e4b-ac0b-f2fac76a3d7f", "id": "141503480340431"}-->',
          },
        ],
        styles: [
          {
            gap: "",
            _uid: "78c5bb1f-aff1-4678-84d0-9635652d2764",
            wrap: false,
            align: "items-center",
            width: "w-full",
            height: "",
            justify: "justify-center",
            component: "shared_styles_breakpoint_options",
            direction: "flex-row",
            max_width: "",
            min_width: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
            _editable:
              '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "78c5bb1f-aff1-4678-84d0-9635652d2764", "id": "141503480340431"}-->',
          },
        ],
        component: "shared_shadcn_container",
        container_as: "header",
        _editable:
          '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "d3f97488-3074-4f29-90d9-6549f1a8d43f", "id": "141503480340431"}-->',
      },
      {
        _uid: "5d7031db-205f-42d2-a0b5-60f7fd135704",
        name: "case-studies",
        items: [
          {
            _uid: "1d90fca7-67e1-4bed-83a5-9210e2d42516",
            name: "case-study",
            items: [
              {
                _uid: "2d56dfe9-65ea-44b8-bf91-41426482892a",
                image: {
                  id: 140495677412865,
                  alt: "",
                  name: "",
                  focus: "",
                  title: "",
                  source: "",
                  filename:
                    "https://a.storyblok.com/f/290156609668258/1200x1200/827039a479/placeholder-1.svg",
                  copyright: "",
                  fieldtype: "asset",
                  meta_data: {},
                  is_external_url: false,
                },
                styles: [
                  {
                    gap: "",
                    _uid: "43f2474d-5dcf-4b27-8d10-236a62f64bb5",
                    wrap: false,
                    align: "",
                    width: "",
                    height: "",
                    margin: [],
                    display: "",
                    justify: "",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "",
                    max_width: "max-w-64",
                    min_width: "",
                    breakpoint: "base",
                    max_height: "",
                    min_height: "",
                    _editable:
                      '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "43f2474d-5dcf-4b27-8d10-236a62f64bb5", "id": "141503480340431"}-->',
                  },
                ],
                caption: "",
                rounded: "lg",
                component: "shared_shadcn_image",
                object_fit: "cover",
                aspect_ratio: "auto",
                data_field_name: "image",
                data_entry_section: "study",
                _editable:
                  '<!--#storyblok#{"name": "shared_shadcn_image", "space": "290156609668258", "uid": "2d56dfe9-65ea-44b8-bf91-41426482892a", "id": "141503480340431"}-->',
              },
              {
                _uid: "89315546-a4aa-482f-8938-9d8d199a144b",
                name: "case-study-content",
                items: [
                  {
                    _uid: "38c57764-2858-412e-b379-952880cf78d7",
                    size: "base",
                    align: "left",
                    color: "default",
                    styles: [
                      {
                        gap: "",
                        _uid: "ccc95c9b-2166-4080-8d98-3972006712e3",
                        wrap: false,
                        align: "",
                        width: "",
                        border: [],
                        height: "",
                        margin: [],
                        shadow: "",
                        display: "",
                        justify: "",
                        padding: [],
                        variant: "",
                        component: "shared_styles_breakpoint_options",
                        direction: "",
                        max_width: "",
                        min_width: "",
                        text_size: "xl",
                        breakpoint: "sm",
                        max_height: "",
                        min_height: "",
                        border_color: "",
                        border_style: "",
                        _editable:
                          '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "ccc95c9b-2166-4080-8d98-3972006712e3", "id": "141503480340431"}-->',
                      },
                    ],
                    weight: "normal",
                    content:
                      "This productivity tool transformed how we collaborate. Our team's workflow improved dramatically, and we've cut meeting time by half while increasing output.",
                    element: "q",
                    component: "shared_shadcn_text",
                    color_dark: {
                      _uid: "c73a280e-4374-423d-bfe5-2a26d687b5ef",
                      color: "#f40000",
                      plugin: "native-color-picker",
                    },
                    color_light: {
                      _uid: "e05272b6-fa5b-491a-8741-c27db87bf1e1",
                      color: "#f40000",
                      plugin: "native-color-picker",
                    },
                    line_height: "normal",
                    letter_spacing: "normal",
                    data_field_name: "quote",
                    data_entry_section: "study",
                    _editable:
                      '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "38c57764-2858-412e-b379-952880cf78d7", "id": "141503480340431"}-->',
                  },
                  {
                    _uid: "5cfa743d-5e8a-4a70-b2de-fcad22a6eda6",
                    name: "",
                    items: [
                      {
                        _uid: "86ad9158-cbbd-49e3-86e1-fb6497d9c056",
                        name: "person",
                        items: [
                          {
                            _uid: "331042b2-6690-42ec-bb9a-f8d3b4c8774f",
                            size: "base",
                            align: "left",
                            color: "default",
                            styles: [],
                            weight: "bold",
                            content: "Michael Rivera",
                            element: "p",
                            component: "shared_shadcn_text",
                            color_dark: {
                              _uid: "efd1fcda-6506-4a26-b8f3-97dd1b9267ef",
                              color: "#f40000",
                              plugin: "native-color-picker",
                            },
                            color_light: {
                              _uid: "995dbe02-f100-4d86-a3e1-fc120b1ef3b0",
                              color: "#f40000",
                              plugin: "native-color-picker",
                            },
                            line_height: "normal",
                            letter_spacing: "normal",
                            data_field_name: "name",
                            data_entry_section: "study",
                            _editable:
                              '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "331042b2-6690-42ec-bb9a-f8d3b4c8774f", "id": "141503480340431"}-->',
                          },
                          {
                            _uid: "12b2f45b-fc2b-4969-9bf6-3044d1e22def",
                            name: "position-and-logo",
                            items: [
                              {
                                _uid: "5d899afe-35d3-4397-a396-188e9fdc9166",
                                size: "base",
                                align: "left",
                                color: "muted",
                                styles: [],
                                weight: "normal",
                                content: "Product Director",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "97c11833-646e-4761-a30c-1feb3bbcc812",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "3055a088-db93-4586-b94d-2346e58c7daa",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "normal",
                                letter_spacing: "normal",
                                data_field_name: "position",
                                data_entry_section: "study",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "5d899afe-35d3-4397-a396-188e9fdc9166", "id": "141503480340431"}-->',
                              },
                              {
                                _uid: "071be5a7-d36f-4a73-b0be-338eb80eb8cf",
                                image: {
                                  id: 140492482516471,
                                  alt: "",
                                  name: "",
                                  focus: "",
                                  title: "",
                                  source: "",
                                  filename:
                                    "https://a.storyblok.com/f/290156609668258/112x27/b884400bc0/fictional-company-logo-2.svg",
                                  copyright: "",
                                  fieldtype: "asset",
                                  meta_data: {},
                                  is_external_url: false,
                                },
                                styles: [],
                                caption: "",
                                rounded: "md",
                                component: "shared_shadcn_image",
                                object_fit: "cover",
                                aspect_ratio: "auto",
                                data_field_name: "company_logo",
                                data_entry_section: "study",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_image", "space": "290156609668258", "uid": "071be5a7-d36f-4a73-b0be-338eb80eb8cf", "id": "141503480340431"}-->',
                              },
                            ],
                            styles: [
                              {
                                gap: "gap-4",
                                _uid: "adb1bb65-a58b-4be7-abe3-04a6c2b032c6",
                                wrap: false,
                                align: "",
                                width: "",
                                height: "",
                                margin: [],
                                display: "",
                                justify: "",
                                padding: [],
                                component: "shared_styles_breakpoint_options",
                                direction: "flex-row",
                                max_width: "",
                                min_width: "",
                                breakpoint: "base",
                                max_height: "",
                                min_height: "",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "adb1bb65-a58b-4be7-abe3-04a6c2b032c6", "id": "141503480340431"}-->',
                              },
                            ],
                            component: "shared_shadcn_container",
                            container_as: "div",
                            _editable:
                              '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "12b2f45b-fc2b-4969-9bf6-3044d1e22def", "id": "141503480340431"}-->',
                          },
                        ],
                        styles: [
                          {
                            gap: "gap-1",
                            _uid: "1c583d55-3071-4297-a809-b02f3d62a58f",
                            wrap: false,
                            align: "",
                            width: "",
                            height: "",
                            margin: [],
                            display: "",
                            justify: "",
                            padding: [],
                            component: "shared_styles_breakpoint_options",
                            direction: "flex-col",
                            max_width: "",
                            min_width: "",
                            breakpoint: "base",
                            max_height: "",
                            min_height: "",
                            _editable:
                              '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "1c583d55-3071-4297-a809-b02f3d62a58f", "id": "141503480340431"}-->',
                          },
                        ],
                        component: "shared_shadcn_container",
                        container_as: "div",
                        _editable:
                          '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "86ad9158-cbbd-49e3-86e1-fb6497d9c056", "id": "141503480340431"}-->',
                      },
                      {
                        _uid: "c50cea3f-3aa6-4162-86db-2768413a0698",
                        name: "",
                        items: [
                          {
                            _uid: "ce70146d-a9f0-4ab8-b6c0-444e621f0547",
                            name: "statistic",
                            items: [
                              {
                                _uid: "5a5aec35-fd25-4898-984d-f96820d649f6",
                                size: "4xl",
                                align: "left",
                                color: "default",
                                styles: [
                                  {
                                    gap: "",
                                    _uid: "67af1122-4cae-455a-b0c6-d5c07b8d0f1e",
                                    wrap: false,
                                    align: "",
                                    width: "",
                                    height: "",
                                    margin: [],
                                    display: "",
                                    justify: "",
                                    padding: [],
                                    component:
                                      "shared_styles_breakpoint_options",
                                    direction: "",
                                    max_width: "",
                                    min_width: "",
                                    text_size: "5xl",
                                    breakpoint: "sm",
                                    max_height: "",
                                    min_height: "",
                                    _editable:
                                      '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "67af1122-4cae-455a-b0c6-d5c07b8d0f1e", "id": "141503480340431"}-->',
                                  },
                                ],
                                weight: "medium",
                                content: "98%",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "fba03986-7a34-4b51-9914-f3ffd5b9c1c6",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "1a1384b1-f120-4ca3-8d56-67908e63cbe3",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "none",
                                letter_spacing: "normal",
                                data_field_name: "headline_number",
                                data_entry_section: "statistic",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "5a5aec35-fd25-4898-984d-f96820d649f6", "id": "141503480340431"}-->',
                              },
                              {
                                _uid: "52122944-f187-4f45-8f4c-3016e583b722",
                                size: "lg",
                                align: "left",
                                color: "default",
                                styles: [],
                                weight: "semibold",
                                content: "Customer Satisfaction",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "caebd186-409f-4f36-b034-2cdf5291fe6e",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "bd836ed8-9b6e-433e-98b7-d827d9a1b630",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "normal",
                                letter_spacing: "normal",
                                data_field_name: "what_it_measures",
                                data_entry_section: "statistic",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "52122944-f187-4f45-8f4c-3016e583b722", "id": "141503480340431"}-->',
                              },
                              {
                                _uid: "15b207fc-b6f1-4e71-a0d9-fc8c82d20d0b",
                                size: "base",
                                align: "left",
                                color: "muted",
                                styles: [],
                                weight: "semibold",
                                content: "From verified reviews",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "caebd186-409f-4f36-b034-2cdf5291fe6e",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "bd836ed8-9b6e-433e-98b7-d827d9a1b630",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "normal",
                                letter_spacing: "normal",
                                data_field_name: "source_or_context",
                                data_entry_section: "statistic",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "15b207fc-b6f1-4e71-a0d9-fc8c82d20d0b", "id": "141503480340431"}-->',
                              },
                            ],
                            styles: [
                              {
                                gap: "gap-2",
                                _uid: "05a1da56-e3a6-4f46-a098-8d9391b6e07a",
                                wrap: false,
                                align: "",
                                width: "",
                                height: "",
                                margin: [],
                                display: "",
                                justify: "",
                                padding: [],
                                component: "shared_styles_breakpoint_options",
                                direction: "flex-col",
                                max_width: "",
                                min_width: "",
                                breakpoint: "base",
                                max_height: "",
                                min_height: "",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "05a1da56-e3a6-4f46-a098-8d9391b6e07a", "id": "141503480340431"}-->',
                              },
                            ],
                            component: "shared_shadcn_container",
                            container_as: "div",
                            _editable:
                              '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "ce70146d-a9f0-4ab8-b6c0-444e621f0547", "id": "141503480340431"}-->',
                          },
                          {
                            _uid: "de68f6c8-102a-4672-bb9e-f8750f802e97",
                            name: "statistic",
                            items: [
                              {
                                _uid: "aed12e4b-b570-4da5-93a6-197b41d840c9",
                                size: "4xl",
                                align: "left",
                                color: "default",
                                styles: [
                                  {
                                    gap: "",
                                    _uid: "7c744eb4-deb4-4cc3-bf01-41e6d4ec2961",
                                    wrap: false,
                                    align: "",
                                    width: "",
                                    height: "",
                                    margin: [],
                                    display: "",
                                    justify: "",
                                    padding: [],
                                    component:
                                      "shared_styles_breakpoint_options",
                                    direction: "",
                                    max_width: "",
                                    min_width: "",
                                    text_size: "5xl",
                                    breakpoint: "sm",
                                    max_height: "",
                                    min_height: "",
                                    _editable:
                                      '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "7c744eb4-deb4-4cc3-bf01-41e6d4ec2961", "id": "141503480340431"}-->',
                                  },
                                ],
                                weight: "medium",
                                content: "3.8x",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "fba03986-7a34-4b51-9914-f3ffd5b9c1c6",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "1a1384b1-f120-4ca3-8d56-67908e63cbe3",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "none",
                                letter_spacing: "normal",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "aed12e4b-b570-4da5-93a6-197b41d840c9", "id": "141503480340431"}-->',
                              },
                              {
                                _uid: "50dc346e-3f71-4d23-8362-9fd85f504467",
                                size: "lg",
                                align: "left",
                                color: "default",
                                styles: [],
                                weight: "semibold",
                                content: "ROI Improvement",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "caebd186-409f-4f36-b034-2cdf5291fe6e",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "bd836ed8-9b6e-433e-98b7-d827d9a1b630",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "normal",
                                letter_spacing: "normal",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "50dc346e-3f71-4d23-8362-9fd85f504467", "id": "141503480340431"}-->',
                              },
                              {
                                _uid: "9c139144-c579-4bdc-9457-d6227f29188a",
                                size: "base",
                                align: "left",
                                color: "muted",
                                styles: [],
                                weight: "semibold",
                                content: "Within first quarter",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "caebd186-409f-4f36-b034-2cdf5291fe6e",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "bd836ed8-9b6e-433e-98b7-d827d9a1b630",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "normal",
                                letter_spacing: "normal",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "9c139144-c579-4bdc-9457-d6227f29188a", "id": "141503480340431"}-->',
                              },
                            ],
                            styles: [
                              {
                                gap: "gap-2",
                                _uid: "38569208-1cd2-408d-bf8a-b1aa3f979d72",
                                wrap: false,
                                align: "",
                                width: "",
                                height: "",
                                margin: [],
                                display: "",
                                justify: "",
                                padding: [],
                                component: "shared_styles_breakpoint_options",
                                direction: "flex-col",
                                max_width: "",
                                min_width: "",
                                breakpoint: "base",
                                max_height: "",
                                min_height: "",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "38569208-1cd2-408d-bf8a-b1aa3f979d72", "id": "141503480340431"}-->',
                              },
                            ],
                            component: "shared_shadcn_container",
                            container_as: "div",
                            _editable:
                              '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "de68f6c8-102a-4672-bb9e-f8750f802e97", "id": "141503480340431"}-->',
                          },
                        ],
                        styles: [
                          {
                            gap: "gap-6",
                            _uid: "0ad190c6-6111-4272-bb58-c215fddf68d8",
                            wrap: false,
                            align: "",
                            width: "",
                            height: "",
                            margin: [],
                            display: "",
                            justify: "",
                            padding: [],
                            component: "shared_styles_breakpoint_options",
                            direction: "flex-row",
                            max_width: "",
                            min_width: "",
                            breakpoint: "base",
                            max_height: "",
                            min_height: "",
                            _editable:
                              '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "0ad190c6-6111-4272-bb58-c215fddf68d8", "id": "141503480340431"}-->',
                          },
                        ],
                        component: "shared_shadcn_container",
                        container_as: "div",
                        data_section_name: "statistic",
                        _editable:
                          '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "c50cea3f-3aa6-4162-86db-2768413a0698", "id": "141503480340431"}-->',
                      },
                    ],
                    styles: [
                      {
                        gap: "gap-10",
                        _uid: "12a548d8-9848-40f3-882a-25e79fabe38d",
                        wrap: false,
                        align: "",
                        width: "",
                        border: [],
                        height: "",
                        margin: [],
                        shadow: "",
                        display: "",
                        justify: "justify-between",
                        padding: [],
                        component: "shared_styles_breakpoint_options",
                        direction: "flex-col",
                        max_width: "",
                        min_width: "",
                        text_size: "",
                        breakpoint: "base",
                        max_height: "",
                        min_height: "",
                        border_color: "",
                        border_style: "",
                        _editable:
                          '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "12a548d8-9848-40f3-882a-25e79fabe38d", "id": "141503480340431"}-->',
                      },
                    ],
                    component: "shared_shadcn_container",
                    container_as: "div",
                    _editable:
                      '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "5cfa743d-5e8a-4a70-b2de-fcad22a6eda6", "id": "141503480340431"}-->',
                  },
                ],
                styles: [
                  {
                    gap: "gap-10",
                    _uid: "24ceaf26-344c-4d7e-a455-8656eac1d075",
                    wrap: false,
                    align: "",
                    width: "",
                    border: [],
                    height: "",
                    margin: [],
                    shadow: "",
                    display: "",
                    justify: "justify-between",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "flex-col",
                    max_width: "",
                    min_width: "",
                    text_size: "",
                    breakpoint: "base",
                    max_height: "",
                    min_height: "",
                    border_color: "",
                    border_style: "",
                    _editable:
                      '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "24ceaf26-344c-4d7e-a455-8656eac1d075", "id": "141503480340431"}-->',
                  },
                ],
                component: "shared_shadcn_container",
                container_as: "div",
                data_section_name: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "89315546-a4aa-482f-8938-9d8d199a144b", "id": "141503480340431"}-->',
              },
            ],
            styles: [
              {
                gap: "",
                _uid: "ac4e819a-e53e-4acc-9fa5-1440a031aa1c",
                wrap: false,
                align: "",
                group: false,
                width: "",
                border: ["border-0"],
                height: "",
                margin: [],
                shadow: "",
                display: "",
                justify: "",
                padding: [],
                variant: "last",
                component: "shared_styles_breakpoint_options",
                direction: "",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
                border_color: "",
                border_style: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "ac4e819a-e53e-4acc-9fa5-1440a031aa1c", "id": "141503480340431"}-->',
              },
              {
                gap: "gap-10",
                _uid: "59047793-ddc0-4962-8fcd-bd7988a74228",
                wrap: false,
                align: "",
                width: "",
                border: ["border-b"],
                height: "",
                margin: [],
                shadow: "",
                display: "flex",
                justify: "",
                padding: ["py-20"],
                component: "shared_styles_breakpoint_options",
                direction: "flex-col",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
                border_color: "border-muted",
                border_style: "",
                border_width: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "59047793-ddc0-4962-8fcd-bd7988a74228", "id": "141503480340431"}-->',
              },
              {
                gap: "",
                _uid: "a981f94f-efed-41ff-b5d0-840f5f9dd0c4",
                wrap: false,
                align: "",
                width: "",
                border: [],
                height: "",
                margin: [],
                shadow: "",
                display: "",
                justify: "",
                padding: [],
                component: "shared_styles_breakpoint_options",
                direction: "flex-row",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "sm",
                max_height: "",
                min_height: "",
                border_color: "",
                border_style: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "a981f94f-efed-41ff-b5d0-840f5f9dd0c4", "id": "141503480340431"}-->',
              },
              {
                gap: "",
                _uid: "ffa587e5-f350-44f8-a913-43ae963cbb6e",
                wrap: false,
                align: "",
                width: "",
                border: ["border-r"],
                height: "",
                margin: [],
                shadow: "",
                display: "",
                justify: "",
                padding: ["pr-16"],
                component: "shared_styles_breakpoint_options",
                direction: "",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "lg",
                max_height: "",
                min_height: "",
                border_color: "",
                border_style: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "ffa587e5-f350-44f8-a913-43ae963cbb6e", "id": "141503480340431"}-->',
              },
              {
                gap: "",
                _uid: "28ec6dcb-1144-4030-bbb9-49f30c120430",
                wrap: false,
                align: "",
                width: "",
                border: [],
                height: "",
                margin: [],
                shadow: "",
                display: "",
                justify: "",
                padding: ["pr-24"],
                component: "shared_styles_breakpoint_options",
                direction: "",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "xl",
                max_height: "",
                min_height: "",
                border_color: "",
                border_style: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "28ec6dcb-1144-4030-bbb9-49f30c120430", "id": "141503480340431"}-->',
              },
            ],
            component: "shared_shadcn_container",
            container_as: "li",
            data_section_name: "study",
            _editable:
              '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "1d90fca7-67e1-4bed-83a5-9210e2d42516", "id": "141503480340431"}-->',
          },
        ],
        styles: [
          {
            gap: "",
            _uid: "845b9faa-d5ef-4840-acc4-37b0edb5c32e",
            wrap: false,
            align: "",
            group: true,
            width: "",
            border: [],
            height: "",
            margin: [],
            shadow: "",
            display: "",
            justify: "",
            padding: [],
            variant: "",
            component: "shared_styles_breakpoint_options",
            direction: "",
            max_width: "",
            min_width: "",
            text_size: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
            border_color: "",
            border_style: "",
            _editable:
              '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "845b9faa-d5ef-4840-acc4-37b0edb5c32e", "id": "141503480340431"}-->',
          },
        ],
        component: "shared_shadcn_container",
        container_as: "ul",
        _editable:
          '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "5d7031db-205f-42d2-a0b5-60f7fd135704", "id": "141503480340431"}-->',
      },
    ],
    styles: [
      {
        gap: "",
        _uid: "8c03adb4-f574-44de-bbb3-20dfc33c2516",
        wrap: false,
        align: "",
        width: "",
        height: "",
        margin: [],
        shadow: "",
        display: "flex",
        justify: "",
        padding: ["px-4", "py-32"],
        variant: "",
        component: "shared_styles_breakpoint_options",
        direction: "flex-col",
        max_width: "",
        min_width: "",
        text_size: "",
        breakpoint: "base",
        max_height: "",
        min_height: "",
        border_color: "",
        border_style: "",
        _editable:
          '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "8c03adb4-f574-44de-bbb3-20dfc33c2516", "id": "141503480340431"}-->',
      },
    ],
    component: "shared_shadcn_container",
    container_as: "section",
    data_section_name: "studies",
    _editable:
      '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "05289be4-5693-482a-8441-ece56a48fe84", "id": "141503480340431"}-->',
  };
}
