import type { CaseStudies2Blok, StatisticInput } from "./case-studies-2.types";

export function generateElements(blok: CaseStudies2Blok) {
  return {
    _uid: blok._uid,
    name: "case-studies-2",
    items: [
      {
        _uid: `${blok._uid}-1`,
        name: "header",
        items: [
          {
            _uid: `${blok._uid}-1-1`,
            name: "hero-wrapper",
            items: [
              {
                _uid: `${blok._uid}-1-1-1`,
                size: "base",
                align: "center",
                color: "primary",
                weight: "semibold",
                content: "4500+ Satisfied Customers",
                element: "p",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: `${blok._uid}-1-1-1-1`,
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: `${blok._uid}-1-1-1-2`,
                  color: "",
                  plugin: "native-color-picker",
                },
                line_height: "normal",
                letter_spacing: "wide",
              },
              {
                _uid: `${blok._uid}-1-1-2`,
                size: "4xl",
                align: "center",
                color: "primary",
                styles: [
                  {
                    gap: "",
                    _uid: `${blok._uid}-1-1-2-1`,
                    wrap: false,
                    align: "",
                    width: "",
                    border: [],
                    height: "",
                    margin: [],
                    shadow: "",
                    display: "",
                    justify: "",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "",
                    max_width: "",
                    min_width: "",
                    text_size: "5xl",
                    breakpoint: "md",
                    max_height: "",
                    min_height: "",
                    border_color: "",
                    border_style: "",
                    border_width: "",
                  },
                ],
                weight: "semibold",
                content: "Real results from real users",
                element: "h2",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: `${blok._uid}-1-1-2-2`,
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: `${blok._uid}-1-1-2-3`,
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                line_height: "",
                letter_spacing: "",
              },
            ],
            styles: [
              {
                gap: "gap-6",
                _uid: `${blok._uid}-1-1-3`,
                wrap: false,
                align: "items-center",
                width: "",
                height: "",
                margin: "",
                display: "",
                justify: "justify-start",
                padding: [],
                component: "shared_styles_breakpoint_options",
                direction: "flex-col",
                max_width: "max-w-2xl",
                min_width: "",
                text_size: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
              },
            ],
            component: "shared_shadcn_container",
            container_as: "hgroup",
          },
        ],
        styles: [
          {
            gap: "",
            _uid: `${blok._uid}-1-2`,
            wrap: false,
            align: "items-center",
            width: "w-full",
            height: "",
            justify: "justify-center",
            component: "shared_styles_breakpoint_options",
            direction: "flex-row",
            max_width: "",
            min_width: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
          },
        ],
        component: "shared_shadcn_container",
        container_as: "header",
      },
      {
        _uid: `${blok._uid}-2`,
        name: "case-studies",
        items: getCaseStudiesItems(blok.studies),
        styles: [
          {
            gap: "",
            _uid: `${blok._uid}-2`,
            wrap: false,
            align: "",
            group: true,
            width: "",
            border: [],
            height: "",
            margin: [],
            shadow: "",
            display: "",
            justify: "",
            padding: [],
            variant: "",
            component: "shared_styles_breakpoint_options",
            direction: "",
            max_width: "",
            min_width: "",
            text_size: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
            border_color: "",
            border_style: "",
          },
        ],
        component: "shared_shadcn_container",
        container_as: "ul",
      },
    ],
    styles: [
      {
        gap: "",
        _uid: `${blok._uid}-3`,
        wrap: false,
        align: "",
        width: "",
        height: "",
        margin: [],
        shadow: "",
        display: "flex",
        justify: "",
        padding: ["px-4", "py-32"],
        variant: "",
        component: "shared_styles_breakpoint_options",
        direction: "flex-col",
        max_width: "",
        min_width: "",
        text_size: "",
        breakpoint: "base",
        max_height: "",
        min_height: "",
        border_color: "",
        border_style: "",
      },
    ],
    component: "shared_shadcn_container",
    container_as: "section",
    sectionBlok: blok,
  };
}

function getCaseStudiesItems(studies: CaseStudies2Blok["studies"]) {
  return studies.map((study) => {
    return {
      _uid: study._uid,
      name: "case-study",
      items: [
        {
          _uid: `${study._uid}-1`,
          image: {
            id: study.image.id,
            alt: study.image.alt,
            name: study.image.name,
            focus: study.image.focus,
            title: study.image.title,
            source: study.image.source,
            filename: study.image.filename,
            copyright: study.image.copyright,
            fieldtype: study.image.fieldtype,
            meta_data: study.image.meta_data,
            is_external_url: study.image.is_external_url,
          },
          styles: [
            {
              gap: "",
              _uid: `${study._uid}-1-1`,
              wrap: false,
              align: "",
              width: "",
              height: "",
              margin: [],
              display: "",
              justify: "",
              padding: [],
              component: "shared_styles_breakpoint_options",
              direction: "",
              max_width: "max-w-64",
              min_width: "",
              breakpoint: "base",
              max_height: "",
              min_height: "",
            },
          ],
          caption: "",
          rounded: "lg",
          component: "shared_shadcn_image",
          object_fit: "cover",
          aspect_ratio: "auto",
        },
        {
          _uid: `${study._uid}-2`,
          name: "case-study-content",
          items: [
            {
              _uid: `${study._uid}-2-1`,
              size: "base",
              align: "left",
              color: "default",
              styles: [
                {
                  gap: "",
                  _uid: `${study._uid}-2-1-1`,
                  wrap: false,
                  align: "",
                  width: "",
                  border: [],
                  height: "",
                  margin: [],
                  shadow: "",
                  display: "",
                  justify: "",
                  padding: [],
                  component: "shared_styles_breakpoint_options",
                  direction: "",
                  max_width: "",
                  min_width: "",
                  text_size: "xl",
                  breakpoint: "sm",
                  max_height: "",
                  min_height: "",
                  border_color: "",
                  border_style: "",
                },
              ],
              weight: "normal",
              content: study.quote,
              element: "q",
              component: "shared_shadcn_text",
              color_dark: {
                _uid: `${study._uid}-2-1-2`,
                color: "#f40000",
                plugin: "native-color-picker",
              },
              color_light: {
                _uid: `${study._uid}-2-1-3`,
                color: "#f40000",
                plugin: "native-color-picker",
              },
              line_height: "normal",
              letter_spacing: "normal",
            },
            {
              _uid: `${study._uid}-2-2`,
              name: "",
              items: [
                {
                  _uid: `${study._uid}-2-2-1`,
                  name: "person",
                  items: [
                    {
                      _uid: `${study._uid}-2-2-1-1`,
                      size: "base",
                      align: "left",
                      color: "default",
                      styles: [],
                      weight: "bold",
                      content: study.name,
                      element: "p",
                      component: "shared_shadcn_text",
                      color_dark: {
                        _uid: `${study._uid}-2-2-1-1-1`,
                        color: "#f40000",
                        plugin: "native-color-picker",
                      },
                      color_light: {
                        _uid: `${study._uid}-2-2-1-1-2`,
                        color: "#f40000",
                        plugin: "native-color-picker",
                      },
                      line_height: "normal",
                      letter_spacing: "normal",
                    },
                    {
                      _uid: `${study._uid}-2-2-1-2`,
                      name: "position-and-logo",
                      items: [
                        {
                          _uid: `${study._uid}-2-2-1-2-1`,
                          size: "base",
                          align: "left",
                          color: "muted",
                          styles: [],
                          weight: "normal",
                          content: study.position,
                          element: "p",
                          component: "shared_shadcn_text",
                          color_dark: {
                            _uid: `${study._uid}-2-2-1-2-1-1`,
                            color: "#f40000",
                            plugin: "native-color-picker",
                          },
                          color_light: {
                            _uid: `${study._uid}-2-2-1-2-1-2`,
                            color: "#f40000",
                            plugin: "native-color-picker",
                          },
                          line_height: "normal",
                          letter_spacing: "normal",
                        },
                        {
                          _uid: `${study._uid}-2-2-1-2-2`,
                          image: {
                            id: study.company_logo.id,
                            alt: study.company_logo.alt,
                            name: study.company_logo.name,
                            focus: study.company_logo.focus,
                            title: study.company_logo.title,
                            source: study.company_logo.source,
                            filename: study.company_logo.filename,
                            copyright: study.company_logo.copyright,
                            fieldtype: study.company_logo.fieldtype,
                            meta_data: study.company_logo.meta_data,
                            is_external_url: study.company_logo.is_external_url,
                          },
                          styles: [],
                          caption: "",
                          rounded: "md",
                          component: "shared_shadcn_image",
                          object_fit: "cover",
                          aspect_ratio: "auto",
                        },
                      ],
                      styles: [
                        {
                          gap: "gap-4",
                          _uid: `${study._uid}-2-2-1-2-3`,
                          wrap: false,
                          align: "",
                          width: "",
                          height: "",
                          margin: [],
                          display: "",
                          justify: "",
                          padding: [],
                          component: "shared_styles_breakpoint_options",
                          direction: "flex-row",
                          max_width: "",
                          min_width: "",
                          breakpoint: "base",
                          max_height: "",
                          min_height: "",
                        },
                      ],
                      component: "shared_shadcn_container",
                      container_as: "div",
                    },
                  ],
                  styles: [
                    {
                      gap: "gap-1",
                      _uid: `${study._uid}-2-2-1-3`,
                      wrap: false,
                      align: "",
                      width: "",
                      height: "",
                      margin: [],
                      display: "",
                      justify: "",
                      padding: [],
                      component: "shared_styles_breakpoint_options",
                      direction: "flex-col",
                      max_width: "",
                      min_width: "",
                      breakpoint: "base",
                      max_height: "",
                      min_height: "",
                    },
                  ],
                  component: "shared_shadcn_container",
                  container_as: "div",
                },
                {
                  _uid: `${study._uid}-2-2-2`,
                  name: "statistics",
                  items: getStatisticsItems(study.statistics),
                  styles: [
                    {
                      gap: "gap-6",
                      _uid: `${study._uid}-2-2-2-1`,
                      wrap: false,
                      align: "",
                      width: "",
                      height: "",
                      margin: [],
                      display: "",
                      justify: "",
                      padding: [],
                      component: "shared_styles_breakpoint_options",
                      direction: "flex-row",
                      max_width: "",
                      min_width: "",
                      breakpoint: "base",
                      max_height: "",
                      min_height: "",
                    },
                  ],
                  component: "shared_shadcn_container",
                  container_as: "div",
                },
              ],
              styles: [
                {
                  gap: "gap-10",
                  _uid: `${study._uid}-2-2-3`,
                  wrap: false,
                  align: "",
                  width: "",
                  border: [],
                  height: "",
                  margin: [],
                  shadow: "",
                  display: "",
                  justify: "justify-between",
                  padding: [],
                  component: "shared_styles_breakpoint_options",
                  direction: "flex-col",
                  max_width: "",
                  min_width: "",
                  text_size: "",
                  breakpoint: "base",
                  max_height: "",
                  min_height: "",
                  border_color: "",
                  border_style: "",
                },
              ],
              component: "shared_shadcn_container",
              container_as: "div",
            },
          ],
          styles: [
            {
              gap: "gap-10",
              _uid: `${study._uid}-2-3`,
              wrap: false,
              align: "",
              width: "",
              border: [],
              height: "",
              margin: [],
              shadow: "",
              display: "",
              justify: "justify-between",
              padding: [],
              component: "shared_styles_breakpoint_options",
              direction: "flex-col",
              max_width: "",
              min_width: "",
              text_size: "",
              breakpoint: "base",
              max_height: "",
              min_height: "",
              border_color: "",
              border_style: "",
            },
          ],
          component: "shared_shadcn_container",
          container_as: "div",
        },
      ],
      styles: [
        {
          gap: "",
          _uid: `${study._uid}-3`,
          wrap: false,
          align: "",
          group: false,
          width: "",
          border: ["border-0"],
          height: "",
          margin: [],
          shadow: "",
          display: "",
          justify: "",
          padding: [],
          variant: "last",
          component: "shared_styles_breakpoint_options",
          direction: "",
          max_width: "",
          min_width: "",
          text_size: "",
          breakpoint: "base",
          max_height: "",
          min_height: "",
          border_color: "",
          border_style: "",
        },
        {
          gap: "gap-10",
          _uid: `${study._uid}-4`,
          wrap: false,
          align: "",
          width: "",
          border: ["border-b"],
          height: "",
          margin: [],
          shadow: "",
          display: "flex",
          justify: "",
          padding: ["py-20"],
          component: "shared_styles_breakpoint_options",
          direction: "flex-col",
          max_width: "",
          min_width: "",
          text_size: "",
          breakpoint: "base",
          max_height: "",
          min_height: "",
          border_color: "border-muted",
          border_style: "",
          border_width: "",
        },
        {
          gap: "",
          _uid: `${study._uid}-5`,
          wrap: false,
          align: "",
          width: "",
          border: [],
          height: "",
          margin: [],
          shadow: "",
          display: "",
          justify: "",
          padding: [],
          component: "shared_styles_breakpoint_options",
          direction: "flex-row",
          max_width: "",
          min_width: "",
          text_size: "",
          breakpoint: "sm",
          max_height: "",
          min_height: "",
          border_color: "",
          border_style: "",
        },
        {
          gap: "",
          _uid: `${study._uid}-6`,
          wrap: false,
          align: "",
          width: "",
          border: ["border-r"],
          height: "",
          margin: [],
          shadow: "",
          display: "",
          justify: "",
          padding: ["pr-16"],
          component: "shared_styles_breakpoint_options",
          direction: "",
          max_width: "",
          min_width: "",
          text_size: "",
          breakpoint: "lg",
          max_height: "",
          min_height: "",
          border_color: "",
          border_style: "",
        },
        {
          gap: "",
          _uid: `${study._uid}-7`,
          wrap: false,
          align: "",
          width: "",
          border: [],
          height: "",
          margin: [],
          shadow: "",
          display: "",
          justify: "",
          padding: ["pr-24"],
          component: "shared_styles_breakpoint_options",
          direction: "",
          max_width: "",
          min_width: "",
          text_size: "",
          breakpoint: "xl",
          max_height: "",
          min_height: "",
          border_color: "",
          border_style: "",
        },
      ],
      component: "shared_shadcn_container",
      container_as: "li",
      sectionBlok: study,
    };
  });
}

function getStatisticsItems(statistics: StatisticInput[]) {
  return statistics.map((statistic) => {
    return {
      _uid: statistic._uid,
      name: "statistic",
      items: [
        {
          _uid: `${statistic._uid}-1`,
          size: "4xl",
          align: "left",
          color: "default",
          styles: [
            {
              gap: "",
              _uid: `${statistic._uid}-1-1`,
              wrap: false,
              align: "",
              width: "",
              height: "",
              margin: [],
              display: "",
              justify: "",
              padding: [],
              component: "shared_styles_breakpoint_options",
              direction: "",
              max_width: "",
              min_width: "",
              text_size: "5xl",
              breakpoint: "sm",
              max_height: "",
              min_height: "",
            },
          ],
          weight: "medium",
          content: statistic.headline_number,
          element: "p",
          component: "shared_shadcn_text",
          color_dark: {
            _uid: `${statistic._uid}-1-2`,
            color: "#f40000",
            plugin: "native-color-picker",
          },
          color_light: {
            _uid: `${statistic._uid}-1-3`,
            color: "#f40000",
            plugin: "native-color-picker",
          },
          line_height: "none",
          letter_spacing: "normal",
        },
        {
          _uid: `${statistic._uid}-2`,
          size: "lg",
          align: "left",
          color: "default",
          styles: [],
          weight: "semibold",
          content: statistic.what_it_measures,
          element: "p",
          component: "shared_shadcn_text",
          color_dark: {
            _uid: `${statistic._uid}-2-1`,
            color: "#f40000",
            plugin: "native-color-picker",
          },
          color_light: {
            _uid: `${statistic._uid}-2-2`,
            color: "#f40000",
            plugin: "native-color-picker",
          },
          line_height: "normal",
          letter_spacing: "normal",
        },
        {
          _uid: `${statistic._uid}-3`,
          size: "base",
          align: "left",
          color: "muted",
          styles: [],
          weight: "semibold",
          content: statistic.source_or_context,
          element: "p",
          component: "shared_shadcn_text",
          color_dark: {
            _uid: `${statistic._uid}-3-1`,
            color: "#f40000",
            plugin: "native-color-picker",
          },
          color_light: {
            _uid: `${statistic._uid}-3-2`,
            color: "#f40000",
            plugin: "native-color-picker",
          },
          line_height: "normal",
          letter_spacing: "normal",
        },
      ],
      styles: [
        {
          gap: "gap-2",
          _uid: `${statistic._uid}-4`,
          wrap: false,
          align: "",
          width: "",
          height: "",
          margin: [],
          display: "",
          justify: "",
          padding: [],
          component: "shared_styles_breakpoint_options",
          direction: "flex-col",
          max_width: "",
          min_width: "",
          breakpoint: "base",
          max_height: "",
          min_height: "",
        },
      ],
      component: "shared_shadcn_container",
      container_as: "div",
      sectionBlok: statistic,
    };
  });
}
