import type { CaseStudies2Blok, StatisticInput } from "./case-studies-2.types";

export function generateElements(blok: CaseStudies2Blok) {
  return {
    _uid: "33dabb22-e464-4d89-8dee-aac8fb6ee74f",
    name: "case-studies-2",
    items: [
      {
        _uid: "5fa62138-ff88-4a91-837c-541baa547115",
        name: "header",
        items: [
          {
            _uid: "cc3c2c94-a007-4feb-9ebd-830c287c5702",
            name: "hero-wrapper",
            items: [
              {
                _uid: "75c06cdc-b3ab-4585-b359-c40b291f5452",
                size: "base",
                align: "center",
                color: "primary",
                weight: "semibold",
                content: "4500+ Satisfied Customers",
                element: "p",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: "1dc19d40-7dfb-4dca-8f42-f923c83e0b79",
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: "4fb8f4fc-e467-43cb-8bb9-c5c83533f549",
                  color: "",
                  plugin: "native-color-picker",
                },
                line_height: "normal",
                letter_spacing: "wide",
              },
              {
                _uid: "be47b3bb-ca01-4e84-9b35-d6dc4f67152f",
                size: "4xl",
                align: "center",
                color: "primary",
                styles: [
                  {
                    gap: "",
                    _uid: "be73cf20-12ce-47f9-8ad0-fe36a782539a",
                    wrap: false,
                    align: "",
                    width: "",
                    border: [],
                    height: "",
                    margin: [],
                    shadow: "",
                    display: "",
                    justify: "",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "",
                    max_width: "",
                    min_width: "",
                    text_size: "5xl",
                    breakpoint: "md",
                    max_height: "",
                    min_height: "",
                    border_color: "",
                    border_style: "",
                    border_width: "",
                  },
                ],
                weight: "semibold",
                content: "Real results from real users",
                element: "h2",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: "ed4ae582-8bed-433f-aa99-a9cf46a193f2",
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: "567d6979-b1d1-403e-872b-1f80afe223e9",
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                line_height: "",
                letter_spacing: "",
              },
            ],
            styles: [
              {
                gap: "gap-6",
                _uid: "a74d33da-243a-4b5d-ad4d-ffb764a2f523",
                wrap: false,
                align: "items-center",
                width: "",
                height: "",
                margin: "",
                display: "",
                justify: "justify-start",
                padding: [],
                component: "shared_styles_breakpoint_options",
                direction: "flex-col",
                max_width: "max-w-2xl",
                min_width: "",
                text_size: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
              },
            ],
            component: "shared_shadcn_container",
            container_as: "hgroup",
          },
        ],
        styles: [
          {
            gap: "",
            _uid: "81c3798d-97a4-4716-816c-345d47f9c761",
            wrap: false,
            align: "items-center",
            width: "w-full",
            height: "",
            justify: "justify-center",
            component: "shared_styles_breakpoint_options",
            direction: "flex-row",
            max_width: "",
            min_width: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
          },
        ],
        component: "shared_shadcn_container",
        container_as: "header",
      },
      {
        _uid: "c77dc262-89ca-4733-a61b-2ade11ae524b",
        name: "case-studies",
        items: getCaseStudiesItems(blok.studies),
        styles: [
          {
            gap: "",
            _uid: "193fcf18-11b2-4a92-893c-be535def1caa",
            wrap: false,
            align: "",
            group: true,
            width: "",
            border: [],
            height: "",
            margin: [],
            shadow: "",
            display: "",
            justify: "",
            padding: [],
            variant: "",
            component: "shared_styles_breakpoint_options",
            direction: "",
            max_width: "",
            min_width: "",
            text_size: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
            border_color: "",
            border_style: "",
          },
        ],
        component: "shared_shadcn_container",
        container_as: "ul",
      },
    ],
    styles: [
      {
        gap: "",
        _uid: "420c2279-4001-4d6e-b7f9-6303a3db30ae",
        wrap: false,
        align: "",
        width: "",
        height: "",
        margin: [],
        shadow: "",
        display: "flex",
        justify: "",
        padding: ["px-4", "py-32"],
        variant: "",
        component: "shared_styles_breakpoint_options",
        direction: "flex-col",
        max_width: "",
        min_width: "",
        text_size: "",
        breakpoint: "base",
        max_height: "",
        min_height: "",
        border_color: "",
        border_style: "",
      },
    ],
    component: "shared_shadcn_container",
    container_as: "section",
  };
}

function getCaseStudiesItems(studies: CaseStudies2Blok["studies"]) {
  return studies.map((study) => {
    return {
      _uid: study._uid,
      name: "case-study",
      items: [
        {
          _uid: "e5265ac2-40f1-4c23-a8eb-d429881d76ba",
          image: {
            id: study.image.id,
            alt: study.image.alt,
            name: study.image.name,
            focus: study.image.focus,
            title: study.image.title,
            source: study.image.source,
            filename: study.image.filename,
            copyright: study.image.copyright,
            fieldtype: study.image.fieldtype,
            meta_data: study.image.meta_data,
            is_external_url: study.image.is_external_url,
          },
          styles: [
            {
              gap: "",
              _uid: "dd742586-c72a-40c5-8762-2fc038c28fb5",
              wrap: false,
              align: "",
              width: "",
              height: "",
              margin: [],
              display: "",
              justify: "",
              padding: [],
              component: "shared_styles_breakpoint_options",
              direction: "",
              max_width: "max-w-64",
              min_width: "",
              breakpoint: "base",
              max_height: "",
              min_height: "",
            },
          ],
          caption: "",
          rounded: "lg",
          component: "shared_shadcn_image",
          object_fit: "cover",
          aspect_ratio: "auto",
        },
        {
          _uid: "238b6c58-eaaa-4c95-8485-444f85693d7f",
          name: "case-study-content",
          items: [
            {
              _uid: "a20c1c17-f0c5-4dff-abfd-3dd01a655394",
              size: "base",
              align: "left",
              color: "default",
              styles: [
                {
                  gap: "",
                  _uid: "be6c8e4f-71ef-44c5-ad6d-a0c1a7d5948b",
                  wrap: false,
                  align: "",
                  width: "",
                  border: [],
                  height: "",
                  margin: [],
                  shadow: "",
                  display: "",
                  justify: "",
                  padding: [],
                  component: "shared_styles_breakpoint_options",
                  direction: "",
                  max_width: "",
                  min_width: "",
                  text_size: "xl",
                  breakpoint: "sm",
                  max_height: "",
                  min_height: "",
                  border_color: "",
                  border_style: "",
                },
              ],
              weight: "normal",
              content: study.quote,
              element: "q",
              component: "shared_shadcn_text",
              color_dark: {
                _uid: "c73a280e-4374-423d-bfe5-2a26d687b5ef",
                color: "#f40000",
                plugin: "native-color-picker",
              },
              color_light: {
                _uid: "e05272b6-fa5b-491a-8741-c27db87bf1e1",
                color: "#f40000",
                plugin: "native-color-picker",
              },
              line_height: "normal",
              letter_spacing: "normal",
            },
            {
              _uid: "156793c2-4317-4ced-bc44-5ec1e9afc8cb",
              name: "",
              items: [
                {
                  _uid: "ffe3646d-0bc0-419a-bc33-3d0175c4159f",
                  name: "person",
                  items: [
                    {
                      _uid: "ed1a9350-abf9-407f-a1fd-30501e26c54e",
                      size: "base",
                      align: "left",
                      color: "default",
                      styles: [],
                      weight: "bold",
                      content: study.name,
                      element: "p",
                      component: "shared_shadcn_text",
                      color_dark: {
                        _uid: "efd1fcda-6506-4a26-b8f3-97dd1b9267ef",
                        color: "#f40000",
                        plugin: "native-color-picker",
                      },
                      color_light: {
                        _uid: "995dbe02-f100-4d86-a3e1-fc120b1ef3b0",
                        color: "#f40000",
                        plugin: "native-color-picker",
                      },
                      line_height: "normal",
                      letter_spacing: "normal",
                    },
                    {
                      _uid: "4aa21bcc-ff44-442f-a466-aa47cfc3ba53",
                      name: "position-and-logo",
                      items: [
                        {
                          _uid: "81ae8578-bff2-4b9e-88ed-6a1db595525c",
                          size: "base",
                          align: "left",
                          color: "muted",
                          styles: [],
                          weight: "normal",
                          content: study.position,
                          element: "p",
                          component: "shared_shadcn_text",
                          color_dark: {
                            _uid: "97c11833-646e-4761-a30c-1feb3bbcc812",
                            color: "#f40000",
                            plugin: "native-color-picker",
                          },
                          color_light: {
                            _uid: "3055a088-db93-4586-b94d-2346e58c7daa",
                            color: "#f40000",
                            plugin: "native-color-picker",
                          },
                          line_height: "normal",
                          letter_spacing: "normal",
                        },
                        {
                          _uid: "6160e6dc-79e0-459a-a0a7-0055f851b2d4",
                          image: {
                            id: study.company_logo.id,
                            alt: study.company_logo.alt,
                            name: study.company_logo.name,
                            focus: study.company_logo.focus,
                            title: study.company_logo.title,
                            source: study.company_logo.source,
                            filename: study.company_logo.filename,
                            copyright: study.company_logo.copyright,
                            fieldtype: study.company_logo.fieldtype,
                            meta_data: study.company_logo.meta_data,
                            is_external_url: study.company_logo.is_external_url,
                          },
                          styles: [],
                          caption: "",
                          rounded: "md",
                          component: "shared_shadcn_image",
                          object_fit: "cover",
                          aspect_ratio: "auto",
                        },
                      ],
                      styles: [
                        {
                          gap: "gap-4",
                          _uid: "b831162d-ea38-4501-a6d6-fcd7a97e8e5c",
                          wrap: false,
                          align: "",
                          width: "",
                          height: "",
                          margin: [],
                          display: "",
                          justify: "",
                          padding: [],
                          component: "shared_styles_breakpoint_options",
                          direction: "flex-row",
                          max_width: "",
                          min_width: "",
                          breakpoint: "base",
                          max_height: "",
                          min_height: "",
                        },
                      ],
                      component: "shared_shadcn_container",
                      container_as: "div",
                    },
                  ],
                  styles: [
                    {
                      gap: "gap-1",
                      _uid: "6a6b1ce6-61dc-4fd4-9a79-2d24e271723a",
                      wrap: false,
                      align: "",
                      width: "",
                      height: "",
                      margin: [],
                      display: "",
                      justify: "",
                      padding: [],
                      component: "shared_styles_breakpoint_options",
                      direction: "flex-col",
                      max_width: "",
                      min_width: "",
                      breakpoint: "base",
                      max_height: "",
                      min_height: "",
                    },
                  ],
                  component: "shared_shadcn_container",
                  container_as: "div",
                },
                {
                  _uid: "4d716fd3-8b83-439f-97d0-e78ea649e065",
                  name: "statistics",
                  items: getStatisticsItems(study.statistics),
                  styles: [
                    {
                      gap: "gap-6",
                      _uid: "ae774b5e-acd9-4af1-9f1a-7a1b5dd12af2",
                      wrap: false,
                      align: "",
                      width: "",
                      height: "",
                      margin: [],
                      display: "",
                      justify: "",
                      padding: [],
                      component: "shared_styles_breakpoint_options",
                      direction: "flex-row",
                      max_width: "",
                      min_width: "",
                      breakpoint: "base",
                      max_height: "",
                      min_height: "",
                    },
                  ],
                  component: "shared_shadcn_container",
                  container_as: "div",
                },
              ],
              styles: [
                {
                  gap: "gap-10",
                  _uid: "8e3f2231-e63e-429a-99a3-d12cf8a9e915",
                  wrap: false,
                  align: "",
                  width: "",
                  border: [],
                  height: "",
                  margin: [],
                  shadow: "",
                  display: "",
                  justify: "justify-between",
                  padding: [],
                  component: "shared_styles_breakpoint_options",
                  direction: "flex-col",
                  max_width: "",
                  min_width: "",
                  text_size: "",
                  breakpoint: "base",
                  max_height: "",
                  min_height: "",
                  border_color: "",
                  border_style: "",
                },
              ],
              component: "shared_shadcn_container",
              container_as: "div",
            },
          ],
          styles: [
            {
              gap: "gap-10",
              _uid: "81731e44-c187-4986-b385-08b1d08992bf",
              wrap: false,
              align: "",
              width: "",
              border: [],
              height: "",
              margin: [],
              shadow: "",
              display: "",
              justify: "justify-between",
              padding: [],
              component: "shared_styles_breakpoint_options",
              direction: "flex-col",
              max_width: "",
              min_width: "",
              text_size: "",
              breakpoint: "base",
              max_height: "",
              min_height: "",
              border_color: "",
              border_style: "",
            },
          ],
          component: "shared_shadcn_container",
          container_as: "div",
        },
      ],
      styles: [
        {
          gap: "",
          _uid: "d6aac2c1-59ef-4b0a-9f4e-5e3f2f8b239a",
          wrap: false,
          align: "",
          group: false,
          width: "",
          border: ["border-0"],
          height: "",
          margin: [],
          shadow: "",
          display: "",
          justify: "",
          padding: [],
          variant: "last",
          component: "shared_styles_breakpoint_options",
          direction: "",
          max_width: "",
          min_width: "",
          text_size: "",
          breakpoint: "base",
          max_height: "",
          min_height: "",
          border_color: "",
          border_style: "",
        },
        {
          gap: "gap-10",
          _uid: "465a30c5-9ce0-497f-bdeb-96b45f5d0d9b",
          wrap: false,
          align: "",
          width: "",
          border: ["border-b"],
          height: "",
          margin: [],
          shadow: "",
          display: "flex",
          justify: "",
          padding: ["py-20"],
          component: "shared_styles_breakpoint_options",
          direction: "flex-col",
          max_width: "",
          min_width: "",
          text_size: "",
          breakpoint: "base",
          max_height: "",
          min_height: "",
          border_color: "border-muted",
          border_style: "",
          border_width: "",
        },
        {
          gap: "",
          _uid: "6c3d1d9a-7fdc-4904-9368-06a4a2eb6e83",
          wrap: false,
          align: "",
          width: "",
          border: [],
          height: "",
          margin: [],
          shadow: "",
          display: "",
          justify: "",
          padding: [],
          component: "shared_styles_breakpoint_options",
          direction: "flex-row",
          max_width: "",
          min_width: "",
          text_size: "",
          breakpoint: "sm",
          max_height: "",
          min_height: "",
          border_color: "",
          border_style: "",
        },
        {
          gap: "",
          _uid: "51e95ddc-bfef-4815-975e-c3a387babaae",
          wrap: false,
          align: "",
          width: "",
          border: ["border-r"],
          height: "",
          margin: [],
          shadow: "",
          display: "",
          justify: "",
          padding: ["pr-16"],
          component: "shared_styles_breakpoint_options",
          direction: "",
          max_width: "",
          min_width: "",
          text_size: "",
          breakpoint: "lg",
          max_height: "",
          min_height: "",
          border_color: "",
          border_style: "",
        },
        {
          gap: "",
          _uid: "b5248e8c-9fab-4c13-b97a-d281b5ba3dc6",
          wrap: false,
          align: "",
          width: "",
          border: [],
          height: "",
          margin: [],
          shadow: "",
          display: "",
          justify: "",
          padding: ["pr-24"],
          component: "shared_styles_breakpoint_options",
          direction: "",
          max_width: "",
          min_width: "",
          text_size: "",
          breakpoint: "xl",
          max_height: "",
          min_height: "",
          border_color: "",
          border_style: "",
        },
      ],
      component: "shared_shadcn_container",
      container_as: "li",
    };
  });
}

function getStatisticsItems(statistics: StatisticInput[]) {
  return statistics.map((statistic) => {
    const statisticUid = (suffix: string) => `${statistic._uid}-${suffix}`;
    return {
      _uid: statistic._uid,
      name: "statistic",
      items: [
        {
          _uid: statisticUid("number"),
          size: "4xl",
          align: "left",
          color: "default",
          styles: [
            {
              gap: "",
              _uid: statisticUid("number-styles"),
              wrap: false,
              align: "",
              width: "",
              height: "",
              margin: [],
              display: "",
              justify: "",
              padding: [],
              component: "shared_styles_breakpoint_options",
              direction: "",
              max_width: "",
              min_width: "",
              text_size: "5xl",
              breakpoint: "sm",
              max_height: "",
              min_height: "",
            },
          ],
          weight: "medium",
          content: statistic.headline_number,
          element: "p",
          component: "shared_shadcn_text",
          color_dark: {
            _uid: statisticUid("number-color-dark"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          color_light: {
            _uid: statisticUid("number-color-light"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          line_height: "none",
          letter_spacing: "normal",
        },
        {
          _uid: statisticUid("label"),
          size: "lg",
          align: "left",
          color: "default",
          styles: [],
          weight: "semibold",
          content: statistic.what_it_measures,
          element: "p",
          component: "shared_shadcn_text",
          color_dark: {
            _uid: statisticUid("label-color-dark"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          color_light: {
            _uid: statisticUid("label-color-light"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          line_height: "normal",
          letter_spacing: "normal",
        },
        {
          _uid: statisticUid("sublabel"),
          size: "base",
          align: "left",
          color: "muted",
          styles: [],
          weight: "semibold",
          content: statistic.source_or_context,
          element: "p",
          component: "shared_shadcn_text",
          color_dark: {
            _uid: statisticUid("sublabel-color-dark"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          color_light: {
            _uid: statisticUid("sublabel-color-light"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          line_height: "normal",
          letter_spacing: "normal",
        },
      ],
      styles: [
        {
          gap: "gap-2",
          _uid: statisticUid("styles"),
          wrap: false,
          align: "",
          width: "",
          height: "",
          margin: [],
          display: "",
          justify: "",
          padding: [],
          component: "shared_styles_breakpoint_options",
          direction: "flex-col",
          max_width: "",
          min_width: "",
          breakpoint: "base",
          max_height: "",
          min_height: "",
        },
      ],
      component: "shared_shadcn_container",
      container_as: "div",
    };
  });
}
