import type { CaseStudies2Blok } from "./case-studies-2.types";
import { storyblokEditable } from "@storyblok/react";

function getEditable(blok: { _uid: string; component: string }) {
  const editableRaw = storyblokEditable(blok);
  if (!editableRaw || editableRaw["data-blok-c"] === undefined) {
    return undefined;
  }
  const editable: {
    name: string;
    space: string;
    uid: string;
    id: string;
  } = JSON.parse(editableRaw["data-blok-c"]);
  return `<!--#storyblok#{"name": "${editable.name}", "space": "${editable.space}", "uid": "${editable.uid}", "id": "${editable.id}-->`;
}

export function generateElements(blok: CaseStudies2Blok) {
  return {
    _uid: "33dabb22-e464-4d89-8dee-aac8fb6ee74f",
    name: "case-studies-2",
    items: [
      {
        _uid: "5fa62138-ff88-4a91-837c-541baa547115",
        name: "header",
        items: [
          {
            _uid: "cc3c2c94-a007-4feb-9ebd-830c287c5702",
            name: "hero-wrapper",
            items: [
              {
                _uid: "75c06cdc-b3ab-4585-b359-c40b291f5452",
                size: "base",
                align: "center",
                color: "primary",
                weight: "semibold",
                content: "4500+ Satisfied Customers",
                element: "p",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: "1dc19d40-7dfb-4dca-8f42-f923c83e0b79",
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: "4fb8f4fc-e467-43cb-8bb9-c5c83533f549",
                  color: "",
                  plugin: "native-color-picker",
                },
                line_height: "normal",
                letter_spacing: "wide",
                _editable:
                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "75c06cdc-b3ab-4585-b359-c40b291f5452", "id": "140419103012578"}-->',
              },
              {
                _uid: "be47b3bb-ca01-4e84-9b35-d6dc4f67152f",
                size: "4xl",
                align: "center",
                color: "primary",
                styles: [
                  {
                    gap: "",
                    _uid: "be73cf20-12ce-47f9-8ad0-fe36a782539a",
                    wrap: false,
                    align: "",
                    width: "",
                    border: [],
                    height: "",
                    margin: [],
                    shadow: "",
                    display: "",
                    justify: "",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "",
                    max_width: "",
                    min_width: "",
                    text_size: "5xl",
                    breakpoint: "md",
                    max_height: "",
                    min_height: "",
                    border_color: "",
                    border_style: "",
                    border_width: "",
                    _editable:
                      '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "be73cf20-12ce-47f9-8ad0-fe36a782539a", "id": "140419103012578"}-->',
                  },
                ],
                weight: "semibold",
                content: "Real results from real users",
                element: "h2",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: "ed4ae582-8bed-433f-aa99-a9cf46a193f2",
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: "567d6979-b1d1-403e-872b-1f80afe223e9",
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                line_height: "",
                letter_spacing: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "be47b3bb-ca01-4e84-9b35-d6dc4f67152f", "id": "140419103012578"}-->',
              },
            ],
            styles: [
              {
                gap: "gap-6",
                _uid: "a74d33da-243a-4b5d-ad4d-ffb764a2f523",
                wrap: false,
                align: "items-center",
                width: "",
                height: "",
                margin: "",
                display: "",
                justify: "justify-start",
                padding: [],
                component: "shared_styles_breakpoint_options",
                direction: "flex-col",
                max_width: "max-w-2xl",
                min_width: "",
                text_size: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "a74d33da-243a-4b5d-ad4d-ffb764a2f523", "id": "140419103012578"}-->',
              },
            ],
            component: "shared_shadcn_container",
            container_as: "hgroup",
            _editable:
              '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "cc3c2c94-a007-4feb-9ebd-830c287c5702", "id": "140419103012578"}-->',
          },
        ],
        styles: [
          {
            gap: "",
            _uid: "81c3798d-97a4-4716-816c-345d47f9c761",
            wrap: false,
            align: "items-center",
            width: "w-full",
            height: "",
            justify: "justify-center",
            component: "shared_styles_breakpoint_options",
            direction: "flex-row",
            max_width: "",
            min_width: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
            _editable:
              '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "81c3798d-97a4-4716-816c-345d47f9c761", "id": "140419103012578"}-->',
          },
        ],
        component: "shared_shadcn_container",
        container_as: "header",
        _editable:
          '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "5fa62138-ff88-4a91-837c-541baa547115", "id": "140419103012578"}-->',
      },
      {
        _uid: "c77dc262-89ca-4733-a61b-2ade11ae524b",
        name: "case-studies",
        // items: getCaseStudiesItems(blok.studies),
        items: [
          {
            _uid: "b892dcc9-dd00-4f55-a64f-7931ab0bb9a4",
            name: "case-study",
            items: [
              {
                _uid: "e5265ac2-40f1-4c23-a8eb-d429881d76ba",
                image: {
                  id: 140495677412865,
                  alt: "",
                  name: "",
                  focus: "",
                  title: "",
                  source: "",
                  filename:
                    "https://a.storyblok.com/f/290156609668258/1200x1200/827039a479/placeholder-1.svg",
                  copyright: "",
                  fieldtype: "asset",
                  meta_data: {},
                  is_external_url: false,
                },
                styles: [
                  {
                    gap: "",
                    _uid: "dd742586-c72a-40c5-8762-2fc038c28fb5",
                    wrap: false,
                    align: "",
                    width: "",
                    height: "",
                    margin: [],
                    display: "",
                    justify: "",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "",
                    max_width: "max-w-64",
                    min_width: "",
                    breakpoint: "base",
                    max_height: "",
                    min_height: "",
                    _editable:
                      '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "dd742586-c72a-40c5-8762-2fc038c28fb5", "id": "140419103012578"}-->',
                  },
                ],
                caption: "",
                rounded: "lg",
                component: "shared_shadcn_image",
                object_fit: "cover",
                aspect_ratio: "auto",
                _editable:
                  '<!--#storyblok#{"name": "shared_shadcn_image", "space": "290156609668258", "uid": "e5265ac2-40f1-4c23-a8eb-d429881d76ba", "id": "140419103012578"}-->',
              },
              {
                _uid: "238b6c58-eaaa-4c95-8485-444f85693d7f",
                name: "case-study-content",
                items: [
                  {
                    _uid: "a20c1c17-f0c5-4dff-abfd-3dd01a655394",
                    size: "base",
                    align: "left",
                    color: "default",
                    styles: [
                      {
                        gap: "",
                        _uid: "be6c8e4f-71ef-44c5-ad6d-a0c1a7d5948b",
                        wrap: false,
                        align: "",
                        width: "",
                        border: [],
                        height: "",
                        margin: [],
                        shadow: "",
                        display: "",
                        justify: "",
                        padding: [],
                        component: "shared_styles_breakpoint_options",
                        direction: "",
                        max_width: "",
                        min_width: "",
                        text_size: "xl",
                        breakpoint: "sm",
                        max_height: "",
                        min_height: "",
                        border_color: "",
                        border_style: "",
                        _editable:
                          '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "be6c8e4f-71ef-44c5-ad6d-a0c1a7d5948b", "id": "140419103012578"}-->',
                      },
                    ],
                    weight: "normal",
                    content:
                      "This productivity tool transformed how we collaborate. Our team's workflow improved dramatically, and we've cut meeting time by half while increasing output.",
                    element: "q",
                    component: "shared_shadcn_text",
                    color_dark: {
                      _uid: "c73a280e-4374-423d-bfe5-2a26d687b5ef",
                      color: "#f40000",
                      plugin: "native-color-picker",
                    },
                    color_light: {
                      _uid: "e05272b6-fa5b-491a-8741-c27db87bf1e1",
                      color: "#f40000",
                      plugin: "native-color-picker",
                    },
                    line_height: "normal",
                    letter_spacing: "normal",
                    _editable:
                      '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "a20c1c17-f0c5-4dff-abfd-3dd01a655394", "id": "140419103012578"}-->',
                  },
                  {
                    _uid: "156793c2-4317-4ced-bc44-5ec1e9afc8cb",
                    name: "",
                    items: [
                      {
                        _uid: "ffe3646d-0bc0-419a-bc33-3d0175c4159f",
                        name: "person",
                        items: [
                          {
                            _uid: "ed1a9350-abf9-407f-a1fd-30501e26c54e",
                            size: "base",
                            align: "left",
                            color: "default",
                            styles: [],
                            weight: "bold",
                            content: "Michael Rivera",
                            element: "p",
                            component: "shared_shadcn_text",
                            color_dark: {
                              _uid: "efd1fcda-6506-4a26-b8f3-97dd1b9267ef",
                              color: "#f40000",
                              plugin: "native-color-picker",
                            },
                            color_light: {
                              _uid: "995dbe02-f100-4d86-a3e1-fc120b1ef3b0",
                              color: "#f40000",
                              plugin: "native-color-picker",
                            },
                            line_height: "normal",
                            letter_spacing: "normal",
                            _editable:
                              '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "ed1a9350-abf9-407f-a1fd-30501e26c54e", "id": "140419103012578"}-->',
                          },
                          {
                            _uid: "4aa21bcc-ff44-442f-a466-aa47cfc3ba53",
                            name: "position-and-logo",
                            items: [
                              {
                                _uid: "81ae8578-bff2-4b9e-88ed-6a1db595525c",
                                size: "base",
                                align: "left",
                                color: "muted",
                                styles: [],
                                weight: "normal",
                                content: "Product Director",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "97c11833-646e-4761-a30c-1feb3bbcc812",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "3055a088-db93-4586-b94d-2346e58c7daa",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "normal",
                                letter_spacing: "normal",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "81ae8578-bff2-4b9e-88ed-6a1db595525c", "id": "140419103012578"}-->',
                              },
                              {
                                _uid: "6160e6dc-79e0-459a-a0a7-0055f851b2d4",
                                image: {
                                  id: 140492482516471,
                                  alt: "",
                                  name: "",
                                  focus: "",
                                  title: "",
                                  source: "",
                                  filename:
                                    "https://a.storyblok.com/f/290156609668258/112x27/b884400bc0/fictional-company-logo-2.svg",
                                  copyright: "",
                                  fieldtype: "asset",
                                  meta_data: {},
                                  is_external_url: false,
                                },
                                styles: [],
                                caption: "",
                                rounded: "md",
                                component: "shared_shadcn_image",
                                object_fit: "cover",
                                aspect_ratio: "auto",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_image", "space": "290156609668258", "uid": "6160e6dc-79e0-459a-a0a7-0055f851b2d4", "id": "140419103012578"}-->',
                              },
                            ],
                            styles: [
                              {
                                gap: "gap-4",
                                _uid: "b831162d-ea38-4501-a6d6-fcd7a97e8e5c",
                                wrap: false,
                                align: "",
                                width: "",
                                height: "",
                                margin: [],
                                display: "",
                                justify: "",
                                padding: [],
                                component: "shared_styles_breakpoint_options",
                                direction: "flex-row",
                                max_width: "",
                                min_width: "",
                                breakpoint: "base",
                                max_height: "",
                                min_height: "",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "b831162d-ea38-4501-a6d6-fcd7a97e8e5c", "id": "140419103012578"}-->',
                              },
                            ],
                            component: "shared_shadcn_container",
                            container_as: "div",
                            _editable:
                              '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "4aa21bcc-ff44-442f-a466-aa47cfc3ba53", "id": "140419103012578"}-->',
                          },
                        ],
                        styles: [
                          {
                            gap: "gap-1",
                            _uid: "6a6b1ce6-61dc-4fd4-9a79-2d24e271723a",
                            wrap: false,
                            align: "",
                            width: "",
                            height: "",
                            margin: [],
                            display: "",
                            justify: "",
                            padding: [],
                            component: "shared_styles_breakpoint_options",
                            direction: "flex-col",
                            max_width: "",
                            min_width: "",
                            breakpoint: "base",
                            max_height: "",
                            min_height: "",
                            _editable:
                              '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "6a6b1ce6-61dc-4fd4-9a79-2d24e271723a", "id": "140419103012578"}-->',
                          },
                        ],
                        component: "shared_shadcn_container",
                        container_as: "div",
                        _editable:
                          '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "ffe3646d-0bc0-419a-bc33-3d0175c4159f", "id": "140419103012578"}-->',
                      },
                      {
                        _uid: "4d716fd3-8b83-439f-97d0-e78ea649e065",
                        name: "",
                        items: [
                          {
                            _uid: "78c4d46a-48ee-4dea-b772-a188efe426d9",
                            name: "statistic",
                            items: [
                              {
                                _uid: "2de6aaf5-5ee0-4c0d-857e-d488b4b2c52b",
                                size: "4xl",
                                align: "left",
                                color: "default",
                                styles: [
                                  {
                                    gap: "",
                                    _uid: "440197f8-1680-49cf-8138-4c5481626e57",
                                    wrap: false,
                                    align: "",
                                    width: "",
                                    height: "",
                                    margin: [],
                                    display: "",
                                    justify: "",
                                    padding: [],
                                    component:
                                      "shared_styles_breakpoint_options",
                                    direction: "",
                                    max_width: "",
                                    min_width: "",
                                    text_size: "5xl",
                                    breakpoint: "sm",
                                    max_height: "",
                                    min_height: "",
                                    _editable:
                                      '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "440197f8-1680-49cf-8138-4c5481626e57", "id": "140419103012578"}-->',
                                  },
                                ],
                                weight: "medium",
                                content: "98%",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "fba03986-7a34-4b51-9914-f3ffd5b9c1c6",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "1a1384b1-f120-4ca3-8d56-67908e63cbe3",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "none",
                                letter_spacing: "normal",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "2de6aaf5-5ee0-4c0d-857e-d488b4b2c52b", "id": "140419103012578"}-->',
                              },
                              {
                                _uid: "c636e625-7b17-4518-a84d-4cffa1131547",
                                size: "lg",
                                align: "left",
                                color: "default",
                                styles: [],
                                weight: "semibold",
                                content: "Customer Satisfaction",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "caebd186-409f-4f36-b034-2cdf5291fe6e",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "bd836ed8-9b6e-433e-98b7-d827d9a1b630",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "normal",
                                letter_spacing: "normal",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "c636e625-7b17-4518-a84d-4cffa1131547", "id": "140419103012578"}-->',
                              },
                              {
                                _uid: "4a79d8dc-c00a-4951-a81c-7dca6972b3d4",
                                size: "base",
                                align: "left",
                                color: "muted",
                                styles: [],
                                weight: "semibold",
                                content: "From verified reviews",
                                element: "p",
                                component: "shared_shadcn_text",
                                color_dark: {
                                  _uid: "caebd186-409f-4f36-b034-2cdf5291fe6e",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                color_light: {
                                  _uid: "bd836ed8-9b6e-433e-98b7-d827d9a1b630",
                                  color: "#f40000",
                                  plugin: "native-color-picker",
                                },
                                line_height: "normal",
                                letter_spacing: "normal",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "4a79d8dc-c00a-4951-a81c-7dca6972b3d4", "id": "140419103012578"}-->',
                              },
                            ],
                            styles: [
                              {
                                gap: "gap-2",
                                _uid: "c225a104-4731-48c3-a921-3c1bb01f5fe6",
                                wrap: false,
                                align: "",
                                width: "",
                                height: "",
                                margin: [],
                                display: "",
                                justify: "",
                                padding: [],
                                component: "shared_styles_breakpoint_options",
                                direction: "flex-col",
                                max_width: "",
                                min_width: "",
                                breakpoint: "base",
                                max_height: "",
                                min_height: "",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "c225a104-4731-48c3-a921-3c1bb01f5fe6", "id": "140419103012578"}-->',
                              },
                            ],
                            component: "shared_shadcn_container",
                            container_as: "div",
                            _editable:
                              '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "78c4d46a-48ee-4dea-b772-a188efe426d9", "id": "140419103012578"}-->',
                          },
                          {
                            _uid: "8c761f84-48e2-40d9-aab9-1b36d4371a0d",
                            name: "statistic",
                            items: getStatistics(
                              blok.studies[0]?.statistics ?? [],
                            ),
                            //     align: "left",
                            //     color: "default",
                            //     styles: [
                            //       {
                            //         gap: "",
                            //         _uid: "11d23afb-e0fe-4c8a-9d07-1655df9615e6",
                            //         wrap: false,
                            //         align: "",
                            //         width: "",
                            //         height: "",
                            //         margin: [],
                            //         display: "",
                            //         justify: "",
                            //         padding: [],
                            //         component:
                            //           "shared_styles_breakpoint_options",
                            //         direction: "",
                            //         max_width: "",
                            //         min_width: "",
                            //         text_size: "5xl",
                            //         breakpoint: "sm",
                            //         max_height: "",
                            //         min_height: "",
                            //         _editable:
                            //           '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "11d23afb-e0fe-4c8a-9d07-1655df9615e6", "id": "140419103012578"}-->',
                            //       },
                            //     ],
                            //     weight: "medium",
                            //     content: "3.8x",
                            //     element: "p",
                            //     component: "shared_shadcn_text",
                            //     color_dark: {
                            //       _uid: "fba03986-7a34-4b51-9914-f3ffd5b9c1c6",
                            //       color: "#f40000",
                            //       plugin: "native-color-picker",
                            //     },
                            //     color_light: {
                            //       _uid: "1a1384b1-f120-4ca3-8d56-67908e63cbe3",
                            //       color: "#f40000",
                            //       plugin: "native-color-picker",
                            //     },
                            //     line_height: "none",
                            //     letter_spacing: "normal",
                            //     _editable:
                            //       '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "84f10158-92d2-4b8f-a84c-dbbf6a48abb4", "id": "140419103012578"}-->',
                            //   },
                            //   {
                            //     _uid: "fb828319-7840-49e8-ab5b-9a018e4bc5f3",
                            //     size: "lg",
                            //     align: "left",
                            //     color: "default",
                            //     styles: [],
                            //     weight: "semibold",
                            //     content: "ROI Improvement",
                            //     element: "p",
                            //     component: "shared_shadcn_text",
                            //     color_dark: {
                            //       _uid: "caebd186-409f-4f36-b034-2cdf5291fe6e",
                            //       color: "#f40000",
                            //       plugin: "native-color-picker",
                            //     },
                            //     color_light: {
                            //       _uid: "bd836ed8-9b6e-433e-98b7-d827d9a1b630",
                            //       color: "#f40000",
                            //       plugin: "native-color-picker",
                            //     },
                            //     line_height: "normal",
                            //     letter_spacing: "normal",
                            //     _editable:
                            //       '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "fb828319-7840-49e8-ab5b-9a018e4bc5f3", "id": "140419103012578"}-->',
                            //   },
                            //   {
                            //     _uid: "4d318151-9e92-4fe3-b002-af5677458bf4",
                            //     size: "base",
                            //     align: "left",
                            //     color: "muted",
                            //     styles: [],
                            //     weight: "semibold",
                            //     content: "Within first quarter",
                            //     element: "p",
                            //     component: "shared_shadcn_text",
                            //     color_dark: {
                            //       _uid: "caebd186-409f-4f36-b034-2cdf5291fe6e",
                            //       color: "#f40000",
                            //       plugin: "native-color-picker",
                            //     },
                            //     color_light: {
                            //       _uid: "bd836ed8-9b6e-433e-98b7-d827d9a1b630",
                            //       color: "#f40000",
                            //       plugin: "native-color-picker",
                            //     },
                            //     line_height: "normal",
                            //     letter_spacing: "normal",
                            //     _editable:
                            //       '<!--#storyblok#{"name": "shared_shadcn_text", "space": "290156609668258", "uid": "4d318151-9e92-4fe3-b002-af5677458bf4", "id": "140419103012578"}-->',
                            //   },
                            // ],
                            styles: [
                              {
                                gap: "gap-2",
                                _uid: "ad9f9727-0daa-410f-a0bd-2fe2cd56242e",
                                wrap: false,
                                align: "",
                                width: "",
                                height: "",
                                margin: [],
                                display: "",
                                justify: "",
                                padding: [],
                                component: "shared_styles_breakpoint_options",
                                direction: "flex-col",
                                max_width: "",
                                min_width: "",
                                breakpoint: "base",
                                max_height: "",
                                min_height: "",
                                _editable:
                                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "ad9f9727-0daa-410f-a0bd-2fe2cd56242e", "id": "140419103012578"}-->',
                              },
                            ],
                            component: "shared_shadcn_container",
                            container_as: "div",
                            _editable:
                              '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "8c761f84-48e2-40d9-aab9-1b36d4371a0d", "id": "140419103012578"}-->',
                          },
                        ],
                        styles: [
                          {
                            gap: "gap-6",
                            _uid: "ae774b5e-acd9-4af1-9f1a-7a1b5dd12af2",
                            wrap: false,
                            align: "",
                            width: "",
                            height: "",
                            margin: [],
                            display: "",
                            justify: "",
                            padding: [],
                            component: "shared_styles_breakpoint_options",
                            direction: "flex-row",
                            max_width: "",
                            min_width: "",
                            breakpoint: "base",
                            max_height: "",
                            min_height: "",
                            _editable:
                              '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "ae774b5e-acd9-4af1-9f1a-7a1b5dd12af2", "id": "140419103012578"}-->',
                          },
                        ],
                        component: "shared_shadcn_container",
                        container_as: "div",
                        _editable:
                          '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "4d716fd3-8b83-439f-97d0-e78ea649e065", "id": "140419103012578"}-->',
                      },
                    ],
                    styles: [
                      {
                        gap: "gap-10",
                        _uid: "8e3f2231-e63e-429a-99a3-d12cf8a9e915",
                        wrap: false,
                        align: "",
                        width: "",
                        border: [],
                        height: "",
                        margin: [],
                        shadow: "",
                        display: "",
                        justify: "justify-between",
                        padding: [],
                        component: "shared_styles_breakpoint_options",
                        direction: "flex-col",
                        max_width: "",
                        min_width: "",
                        text_size: "",
                        breakpoint: "base",
                        max_height: "",
                        min_height: "",
                        border_color: "",
                        border_style: "",
                        _editable:
                          '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "8e3f2231-e63e-429a-99a3-d12cf8a9e915", "id": "140419103012578"}-->',
                      },
                    ],
                    component: "shared_shadcn_container",
                    container_as: "div",
                    _editable:
                      '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "156793c2-4317-4ced-bc44-5ec1e9afc8cb", "id": "140419103012578"}-->',
                  },
                ],
                styles: [
                  {
                    gap: "gap-10",
                    _uid: "81731e44-c187-4986-b385-08b1d08992bf",
                    wrap: false,
                    align: "",
                    width: "",
                    border: [],
                    height: "",
                    margin: [],
                    shadow: "",
                    display: "",
                    justify: "justify-between",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "flex-col",
                    max_width: "",
                    min_width: "",
                    text_size: "",
                    breakpoint: "base",
                    max_height: "",
                    min_height: "",
                    border_color: "",
                    border_style: "",
                    _editable:
                      '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "81731e44-c187-4986-b385-08b1d08992bf", "id": "140419103012578"}-->',
                  },
                ],
                component: "shared_shadcn_container",
                container_as: "div",
                _editable:
                  '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "238b6c58-eaaa-4c95-8485-444f85693d7f", "id": "140419103012578"}-->',
              },
            ],
            styles: [
              {
                gap: "",
                _uid: "d6aac2c1-59ef-4b0a-9f4e-5e3f2f8b239a",
                wrap: false,
                align: "",
                group: false,
                width: "",
                border: ["border-0"],
                height: "",
                margin: [],
                shadow: "",
                display: "",
                justify: "",
                padding: [],
                variant: "last",
                component: "shared_styles_breakpoint_options",
                direction: "",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
                border_color: "",
                border_style: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "d6aac2c1-59ef-4b0a-9f4e-5e3f2f8b239a", "id": "140419103012578"}-->',
              },
              {
                gap: "gap-10",
                _uid: "465a30c5-9ce0-497f-bdeb-96b45f5d0d9b",
                wrap: false,
                align: "",
                width: "",
                border: ["border-b"],
                height: "",
                margin: [],
                shadow: "",
                display: "flex",
                justify: "",
                padding: ["py-20"],
                component: "shared_styles_breakpoint_options",
                direction: "flex-col",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
                border_color: "border-muted",
                border_style: "",
                border_width: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "465a30c5-9ce0-497f-bdeb-96b45f5d0d9b", "id": "140419103012578"}-->',
              },
              {
                gap: "",
                _uid: "6c3d1d9a-7fdc-4904-9368-06a4a2eb6e83",
                wrap: false,
                align: "",
                width: "",
                border: [],
                height: "",
                margin: [],
                shadow: "",
                display: "",
                justify: "",
                padding: [],
                component: "shared_styles_breakpoint_options",
                direction: "flex-row",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "sm",
                max_height: "",
                min_height: "",
                border_color: "",
                border_style: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "6c3d1d9a-7fdc-4904-9368-06a4a2eb6e83", "id": "140419103012578"}-->',
              },
              {
                gap: "",
                _uid: "51e95ddc-bfef-4815-975e-c3a387babaae",
                wrap: false,
                align: "",
                width: "",
                border: ["border-r"],
                height: "",
                margin: [],
                shadow: "",
                display: "",
                justify: "",
                padding: ["pr-16"],
                component: "shared_styles_breakpoint_options",
                direction: "",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "lg",
                max_height: "",
                min_height: "",
                border_color: "",
                border_style: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "51e95ddc-bfef-4815-975e-c3a387babaae", "id": "140419103012578"}-->',
              },
              {
                gap: "",
                _uid: "b5248e8c-9fab-4c13-b97a-d281b5ba3dc6",
                wrap: false,
                align: "",
                width: "",
                border: [],
                height: "",
                margin: [],
                shadow: "",
                display: "",
                justify: "",
                padding: ["pr-24"],
                component: "shared_styles_breakpoint_options",
                direction: "",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "xl",
                max_height: "",
                min_height: "",
                border_color: "",
                border_style: "",
                _editable:
                  '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "b5248e8c-9fab-4c13-b97a-d281b5ba3dc6", "id": "140419103012578"}-->',
              },
            ],
            component: "shared_shadcn_container",
            container_as: "li",
            _editable:
              '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "b892dcc9-dd00-4f55-a64f-7931ab0bb9a4", "id": "140419103012578"}-->',
          },
        ],
        styles: [
          {
            gap: "",
            _uid: "193fcf18-11b2-4a92-893c-be535def1caa",
            wrap: false,
            align: "",
            group: true,
            width: "",
            border: [],
            height: "",
            margin: [],
            shadow: "",
            display: "",
            justify: "",
            padding: [],
            variant: "",
            component: "shared_styles_breakpoint_options",
            direction: "",
            max_width: "",
            min_width: "",
            text_size: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
            border_color: "",
            border_style: "",
            _editable:
              '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "193fcf18-11b2-4a92-893c-be535def1caa", "id": "140419103012578"}-->',
          },
        ],
        component: "shared_shadcn_container",
        container_as: "ul",
        _editable:
          '<!--#storyblok#{"name": "shared_shadcn_container", "space": "290156609668258", "uid": "c77dc262-89ca-4733-a61b-2ade11ae524b", "id": "140419103012578"}-->',
      },
    ],
    styles: [
      {
        gap: "",
        _uid: "420c2279-4001-4d6e-b7f9-6303a3db30ae",
        wrap: false,
        align: "",
        width: "",
        height: "",
        margin: [],
        shadow: "",
        display: "flex",
        justify: "",
        padding: ["px-4", "py-32"],
        variant: "",
        component: "shared_styles_breakpoint_options",
        direction: "flex-col",
        max_width: "",
        min_width: "",
        text_size: "",
        breakpoint: "base",
        max_height: "",
        min_height: "",
        border_color: "",
        border_style: "",
        _editable:
          '<!--#storyblok#{"name": "shared_styles_breakpoint_options", "space": "290156609668258", "uid": "420c2279-4001-4d6e-b7f9-6303a3db30ae", "id": "140419103012578"}-->',
      },
    ],
    component: "shared_shadcn_container",
    container_as: "section",
    _editable: getEditable(blok),
  };
  const uid = (suffix: string) => `${blok._uid}-${suffix}`;
  //   console.log(getCaseStudiesItems(blok.studies));
  return {
    _uid: blok._uid,
    name: "case-studies-2",
    items: [
      {
        _uid: uid("header"),
        name: "header",
        items: [
          {
            _uid: uid("hero-wrapper"),
            name: "hero-wrapper",
            items: [
              {
                _uid: uid("hero-text-1"),
                size: "base",
                align: "center",
                color: "primary",
                weight: "semibold",
                content: blok.description,
                element: "p",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: uid("hero-text-1-color-dark"),
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: uid("hero-text-1-color-light"),
                  color: "",
                  plugin: "native-color-picker",
                },
                line_height: "normal",
                letter_spacing: "wide",
              },
              {
                _uid: uid("hero-text-2"),
                size: "4xl",
                align: "center",
                color: "primary",
                styles: [
                  {
                    gap: "",
                    _uid: uid("hero-text-2-styles"),
                    wrap: false,
                    align: "",
                    width: "",
                    border: [],
                    height: "",
                    margin: [],
                    shadow: "",
                    display: "",
                    justify: "",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "",
                    max_width: "",
                    min_width: "",
                    text_size: "5xl",
                    breakpoint: "md",
                    max_height: "",
                    min_height: "",
                    border_color: "",
                    border_style: "",
                    border_width: "",
                  },
                ],
                weight: "semibold",
                content: blok.name,
                element: "h2",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: uid("hero-text-2-color-dark"),
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: uid("hero-text-2-color-light"),
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                line_height: "",
                letter_spacing: "",
              },
            ],
            styles: [
              {
                gap: "gap-6",
                _uid: uid("hero-wrapper-styles"),
                wrap: false,
                align: "items-center",
                width: "",
                height: "",
                margin: "",
                display: "",
                justify: "justify-start",
                padding: [],
                component: "shared_styles_breakpoint_options",
                direction: "flex-col",
                max_width: "max-w-2xl",
                min_width: "",
                text_size: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
              },
            ],
            component: "shared_shadcn_container",
            container_as: "hgroup",
          },
        ],
        styles: [
          {
            gap: "",
            _uid: uid("header-styles"),
            wrap: false,
            align: "items-center",
            width: "w-full",
            height: "",
            justify: "justify-center",
            component: "shared_styles_breakpoint_options",
            direction: "flex-row",
            max_width: "",
            min_width: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
          },
        ],
        component: "shared_shadcn_container",
        container_as: "header",
      },
      {
        _uid: uid("case-studies"),
        name: "case-studies",
        items: [
          {
            _uid: uid("case-studies-image"),
            image: {
              id: 140495677412865,
              alt: blok.studies[0]?.image.alt,
              name: "",
              focus: "",
              title: "",
              source: "",
              filename: blok.studies[0]?.image.filename,
              copyright: "",
              fieldtype: "asset",
              meta_data: {},
              is_external_url: false,
            },
            styles: [
              {
                gap: "",
                _uid: uid("case-studies-image-styles"),
                wrap: false,
                align: "",
                width: "",
                height: "",
                margin: [],
                display: "",
                justify: "",
                padding: [],
                component: "shared_styles_breakpoint_options",
                direction: "",
                max_width: "max-w-64",
                min_width: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
              },
            ],
            caption: "",
            rounded: "lg",
            component: "shared_shadcn_image",
            object_fit: "cover",
            aspect_ratio: "auto",
          },
        ],
        // items: getCaseStudiesItems(blok.studies),
        styles: [
          {
            _uid: uid("case-studies-item"),
            name: "case-studies-item",

            component: "shared_shadcn_container",
            container_as: "li",
          },
          {
            gap: "",
            _uid: uid("case-studies-container-styles"),
            wrap: false,
            align: "",
            group: true,
            width: "",
            border: [],
            height: "",
            margin: [],
            shadow: "",
            display: "",
            justify: "",
            padding: [],
            variant: "",
            component: "shared_styles_breakpoint_options",
            direction: "",
            max_width: "",
            min_width: "",
            text_size: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
            border_color: "",
            border_style: "",
          },
        ],
        component: "shared_shadcn_container",
        container_as: "ul",
      },
    ],
    styles: [
      {
        gap: "",
        _uid: uid("section-root-styles"),
        wrap: false,
        align: "",
        width: "",
        height: "",
        margin: [],
        shadow: "",
        display: "flex",
        justify: "",
        padding: ["px-4", "py-32"],
        variant: "",
        component: "shared_styles_breakpoint_options",
        direction: "flex-col",
        max_width: "",
        min_width: "",
        text_size: "",
        breakpoint: "base",
        max_height: "",
        min_height: "",
        border_color: "",
        border_style: "",
      },
    ],
    component: "shared_shadcn_container",
    container_as: "section",
  };
}

function getCaseStudiesItems(studies: CaseStudies2Blok["studies"]) {
  return studies.map((study) => {
    const studyUid = (suffix: string) => `${study._uid}-${suffix}`;
    return [
      {
        _uid: study._uid,
        name: "case-study",
        items: [
          {
            _uid: studyUid("image"),
            image: {
              id: 140495677412865,
              alt: study.image.alt,
              name: "",
              focus: "",
              title: "",
              source: "",
              filename: study.image.filename,
              copyright: "",
              fieldtype: "asset",
              meta_data: {},
              is_external_url: false,
            },
            styles: [
              {
                gap: "",
                _uid: studyUid("image-styles"),
                wrap: false,
                align: "",
                width: "",
                height: "",
                margin: [],
                display: "",
                justify: "",
                padding: [],
                component: "shared_styles_breakpoint_options",
                direction: "",
                max_width: "max-w-64",
                min_width: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
              },
            ],
            caption: "",
            rounded: "lg",
            component: "shared_shadcn_image",
            object_fit: "cover",
            aspect_ratio: "auto",
          },
          {
            _uid: studyUid("content"),
            name: "case-study-content",
            items: [
              {
                _uid: studyUid("content-title"),
                size: "base",
                align: "left",
                color: "default",
                styles: [
                  {
                    gap: "",
                    _uid: studyUid("content-title-styles"),
                    wrap: false,
                    align: "",
                    width: "",
                    border: [],
                    height: "",
                    margin: [],
                    shadow: "",
                    display: "",
                    justify: "",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "",
                    max_width: "",
                    min_width: "",
                    text_size: "xl",
                    breakpoint: "sm",
                    max_height: "",
                    min_height: "",
                    border_color: "",
                    border_style: "",
                  },
                ],
                weight: "normal",
                content: study.quote,
                element: "q",
                component: "shared_shadcn_text",
                color_dark: {
                  _uid: studyUid("content-title-color-dark"),
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                color_light: {
                  _uid: studyUid("content-title-color-light"),
                  color: "#f40000",
                  plugin: "native-color-picker",
                },
                line_height: "normal",
                letter_spacing: "normal",
              },
              {
                _uid: studyUid("person-wrapper"),
                name: "",
                items: [
                  {
                    _uid: studyUid("person"),
                    name: "person",
                    items: [
                      {
                        _uid: studyUid("person-name"),
                        size: "base",
                        align: "left",
                        color: "default",
                        styles: [],
                        weight: "bold",
                        content: study.name,
                        element: "p",
                        component: "shared_shadcn_text",
                        color_dark: {
                          _uid: studyUid("person-name-color-dark"),
                          color: "#f40000",
                          plugin: "native-color-picker",
                        },
                        color_light: {
                          _uid: studyUid("person-name-color-light"),
                          color: "#f40000",
                          plugin: "native-color-picker",
                        },
                        line_height: "normal",
                        letter_spacing: "normal",
                      },
                      {
                        _uid: studyUid("position-and-logo"),
                        name: "position-and-logo",
                        items: [
                          {
                            _uid: studyUid("position"),
                            size: "base",
                            align: "left",
                            color: "muted",
                            styles: [],
                            weight: "normal",
                            content: study.position,
                            element: "p",
                            component: "shared_shadcn_text",
                            color_dark: {
                              _uid: studyUid("position-color-dark"),
                              color: "#f40000",
                              plugin: "native-color-picker",
                            },
                            color_light: {
                              _uid: studyUid("position-color-light"),
                              color: "#f40000",
                              plugin: "native-color-picker",
                            },
                            line_height: "normal",
                            letter_spacing: "normal",
                          },
                          {
                            _uid: studyUid("logo"),
                            image: {
                              id: 140492482516471,
                              alt: study.company_logo.alt,
                              name: "",
                              focus: "",
                              title: "",
                              source: "",
                              filename: study.company_logo.filename,
                              copyright: "",
                              fieldtype: "asset",
                              meta_data: {},
                              is_external_url: false,
                            },
                            styles: [],
                            caption: "",
                            rounded: "md",
                            component: "shared_shadcn_image",
                            object_fit: "cover",
                            aspect_ratio: "auto",
                          },
                        ],
                        styles: [
                          {
                            gap: "gap-4",
                            _uid: studyUid("position-and-logo-styles"),
                            wrap: false,
                            align: "",
                            width: "",
                            height: "",
                            margin: [],
                            display: "",
                            justify: "",
                            padding: [],
                            component: "shared_styles_breakpoint_options",
                            direction: "flex-row",
                            max_width: "",
                            min_width: "",
                            breakpoint: "base",
                            max_height: "",
                            min_height: "",
                          },
                        ],
                        component: "shared_shadcn_container",
                        container_as: "div",
                      },
                    ],
                    styles: [
                      {
                        gap: "gap-1",
                        _uid: studyUid("person-styles"),
                        wrap: false,
                        align: "",
                        width: "",
                        height: "",
                        margin: [],
                        display: "",
                        justify: "",
                        padding: [],
                        component: "shared_styles_breakpoint_options",
                        direction: "flex-col",
                        max_width: "",
                        min_width: "",
                        breakpoint: "base",
                        max_height: "",
                        min_height: "",
                      },
                    ],
                    component: "shared_shadcn_container",
                    container_as: "div",
                  },
                  {
                    _uid: studyUid("statistics-wrapper"),
                    name: "",
                    items: getStatistics(study.statistics),
                    styles: [
                      {
                        gap: "gap-6",
                        _uid: studyUid("statistics-styles"),
                        wrap: false,
                        align: "",
                        width: "",
                        height: "",
                        margin: [],
                        display: "",
                        justify: "",
                        padding: [],
                        component: "shared_styles_breakpoint_options",
                        direction: "flex-row",
                        max_width: "",
                        min_width: "",
                        breakpoint: "base",
                        max_height: "",
                        min_height: "",
                      },
                    ],
                    component: "shared_shadcn_container",
                    container_as: "div",
                  },
                ],
                styles: [
                  {
                    gap: "gap-10",
                    _uid: studyUid("content-styles"),
                    wrap: false,
                    align: "",
                    width: "",
                    border: [],
                    height: "",
                    margin: [],
                    shadow: "",
                    display: "",
                    justify: "justify-between",
                    padding: [],
                    component: "shared_styles_breakpoint_options",
                    direction: "flex-col",
                    max_width: "",
                    min_width: "",
                    text_size: "",
                    breakpoint: "base",
                    max_height: "",
                    min_height: "",
                    border_color: "",
                    border_style: "",
                  },
                ],
                component: "shared_shadcn_container",
                container_as: "div",
              },
            ],
            styles: [
              {
                gap: "gap-10",
                _uid: studyUid("styles"),
                wrap: false,
                align: "",
                width: "",
                border: [],
                height: "",
                margin: [],
                shadow: "",
                display: "",
                justify: "justify-between",
                padding: [],
                component: "shared_styles_breakpoint_options",
                direction: "flex-col",
                max_width: "",
                min_width: "",
                text_size: "",
                breakpoint: "base",
                max_height: "",
                min_height: "",
                border_color: "",
                border_style: "",
              },
            ],
            component: "shared_shadcn_container",
            container_as: "div",
          },
        ],
        styles: [
          {
            gap: "",
            _uid: studyUid("item-styles-last"),
            wrap: false,
            align: "",
            group: false,
            width: "",
            border: ["border-0"],
            height: "",
            margin: [],
            shadow: "",
            display: "",
            justify: "",
            padding: [],
            variant: "last",
            component: "shared_styles_breakpoint_options",
            direction: "",
            max_width: "",
            min_width: "",
            text_size: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
            border_color: "",
            border_style: "",
          },
          {
            gap: "gap-10",
            _uid: studyUid("item-styles-border"),
            wrap: false,
            align: "",
            width: "",
            border: ["border-b"],
            height: "",
            margin: [],
            shadow: "",
            display: "flex",
            justify: "",
            padding: ["py-20"],
            component: "shared_styles_breakpoint_options",
            direction: "flex-col",
            max_width: "",
            min_width: "",
            text_size: "",
            breakpoint: "base",
            max_height: "",
            min_height: "",
            border_color: "border-muted",
            border_style: "",
            border_width: "",
          },
          {
            gap: "",
            _uid: studyUid("case-studies-ul-styles-base"),
            wrap: false,
            align: "",
            width: "",
            border: [],
            height: "",
            margin: [],
            shadow: "",
            display: "",
            justify: "",
            padding: [],
            component: "shared_styles_breakpoint_options",
            direction: "flex-row",
            max_width: "",
            min_width: "",
            text_size: "",
            breakpoint: "sm",
            max_height: "",
            min_height: "",
            border_color: "",
            border_style: "",
          },
          {
            gap: "",
            _uid: studyUid("case-studies-ul-styles-lg-border"),
            wrap: false,
            align: "",
            width: "",
            border: ["border-r"],
            height: "",
            margin: [],
            shadow: "",
            display: "",
            justify: "",
            padding: ["pr-16"],
            component: "shared_styles_breakpoint_options",
            direction: "",
            max_width: "",
            min_width: "",
            text_size: "",
            breakpoint: "lg",
            max_height: "",
            min_height: "",
            border_color: "",
            border_style: "",
          },
          {
            gap: "",
            _uid: studyUid("case-studies-ul-styles-lg"),
            wrap: false,
            align: "",
            width: "",
            border: [],
            height: "",
            margin: [],
            shadow: "",
            display: "",
            justify: "",
            padding: ["pr-24"],
            component: "shared_styles_breakpoint_options",
            direction: "",
            max_width: "",
            min_width: "",
            text_size: "",
            breakpoint: "xl",
            max_height: "",
            min_height: "",
            border_color: "",
            border_style: "",
          },
        ],
        component: "shared_shadcn_container",
        container_as: "li",
      },
    ];
  });
}

function getStatistics(
  statistics: CaseStudies2Blok["studies"][number]["statistics"],
) {
  return statistics.map((statistic) => {
    const statisticUid = (suffix: string) => `${statistic._uid}-${suffix}`;
    return {
      _uid: statistic._uid,
      name: "statistic",
      items: [
        {
          _uid: statisticUid("number"),
          size: "4xl",
          align: "left",
          color: "default",
          styles: [
            {
              gap: "",
              _uid: statisticUid("number-styles"),
              wrap: false,
              align: "",
              width: "",
              height: "",
              margin: [],
              display: "",
              justify: "",
              padding: [],
              component: "shared_styles_breakpoint_options",
              direction: "",
              max_width: "",
              min_width: "",
              text_size: "5xl",
              breakpoint: "sm",
              max_height: "",
              min_height: "",
            },
          ],
          weight: "medium",
          content: statistic.headline_number,
          element: "p",
          component: "shared_shadcn_text",
          color_dark: {
            _uid: statisticUid("number-color-dark"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          color_light: {
            _uid: statisticUid("number-color-light"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          line_height: "none",
          letter_spacing: "normal",
        },
        {
          _uid: statisticUid("label"),
          size: "lg",
          align: "left",
          color: "default",
          styles: [],
          weight: "semibold",
          content: statistic.what_it_measures,
          element: "p",
          component: "shared_shadcn_text",
          color_dark: {
            _uid: statisticUid("label-color-dark"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          color_light: {
            _uid: statisticUid("label-color-light"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          line_height: "normal",
          letter_spacing: "normal",
        },
        {
          _uid: statisticUid("sublabel"),
          size: "base",
          align: "left",
          color: "muted",
          styles: [],
          weight: "semibold",
          content: statistic.source_or_context,
          element: "p",
          component: "shared_shadcn_text",
          color_dark: {
            _uid: statisticUid("sublabel-color-dark"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          color_light: {
            _uid: statisticUid("sublabel-color-light"),
            color: "#f40000",
            plugin: "native-color-picker",
          },
          line_height: "normal",
          letter_spacing: "normal",
        },
      ],
      styles: [
        {
          gap: "gap-2",
          _uid: statisticUid("styles"),
          wrap: false,
          align: "",
          width: "",
          height: "",
          margin: [],
          display: "",
          justify: "",
          padding: [],
          component: "shared_styles_breakpoint_options",
          direction: "flex-col",
          max_width: "",
          min_width: "",
          breakpoint: "base",
          max_height: "",
          min_height: "",
        },
      ],
      component: "shared_shadcn_container",
      container_as: "div",
    };
  });
}
